ALTER TABLE "business_conversation_escalations" DROP CONSTRAINT "business_conversation_escalations_reason_check";--> statement-breakpoint
ALTER TABLE "business_conversations" DROP CONSTRAINT "business_conversations_handoff_reason_check";--> statement-breakpoint
ALTER TABLE "support_ai_jobs" DROP CONSTRAINT "support_ai_jobs_outcome_check";--> statement-breakpoint
ALTER TABLE "support_ai_jobs" DROP CONSTRAINT "support_ai_jobs_handoff_reason_check";--> statement-breakpoint
ALTER TABLE "support_ai_configs" ADD COLUMN "max_consecutive_clarifying_questions" integer DEFAULT 2 NOT NULL;--> statement-breakpoint
ALTER TABLE "business_conversation_escalations" ADD CONSTRAINT "business_conversation_escalations_reason_check" CHECK (reason IN ('SEND_OUTCOME_UNKNOWN', 'TRANSPORT_REFUSED', 'AI_REQUESTED', 'HANDOFF_TOPIC', 'HUMAN_REQUESTED', 'TOPIC_NOT_ALLOWED', 'LOW_CONFIDENCE', 'REPLY_OUT_OF_BOUNDS', 'DECISION_NOT_REPLY', 'AI_OUTPUT_INVALID', 'AI_UNAVAILABLE', 'ACCOUNT_UNDER_REVIEW', 'IDENTITY_UNVERIFIED', 'CUSTOMER_BLOCKED', 'INSUFFICIENT_GROUNDING', 'LOOP_GUARD', 'UNSUPPORTED_CONTENT', 'REPLY_STALE', 'CLARIFYING_LIMIT'));--> statement-breakpoint
ALTER TABLE "business_conversations" ADD CONSTRAINT "business_conversations_handoff_reason_check" CHECK (handoff_reason IN ('SEND_OUTCOME_UNKNOWN', 'TRANSPORT_REFUSED', 'AI_REQUESTED', 'HANDOFF_TOPIC', 'HUMAN_REQUESTED', 'TOPIC_NOT_ALLOWED', 'LOW_CONFIDENCE', 'REPLY_OUT_OF_BOUNDS', 'DECISION_NOT_REPLY', 'AI_OUTPUT_INVALID', 'AI_UNAVAILABLE', 'ACCOUNT_UNDER_REVIEW', 'IDENTITY_UNVERIFIED', 'CUSTOMER_BLOCKED', 'INSUFFICIENT_GROUNDING', 'LOOP_GUARD', 'UNSUPPORTED_CONTENT', 'REPLY_STALE', 'CLARIFYING_LIMIT'));--> statement-breakpoint
ALTER TABLE "support_ai_configs" ADD CONSTRAINT "support_ai_configs_clarifying_check" CHECK (max_consecutive_clarifying_questions BETWEEN 1 AND 10);--> statement-breakpoint
ALTER TABLE "support_ai_jobs" ADD CONSTRAINT "support_ai_jobs_outcome_check" CHECK (outcome IS NULL OR outcome IN ('sent', 'sent_clarifying', 'dropped_mode', 'dropped_epoch', 'dropped_state', 'dropped_coalesced', 'dropped_connection', 'dropped_scope', 'guard_content', 'guard_customer_blocked', 'guard_consecutive', 'guard_window', 'guard_decision', 'guard_handoff_topic', 'guard_human_requested', 'guard_topic_allowlist', 'guard_identity', 'guard_account_review', 'guard_confidence', 'guard_reply_bounds', 'guard_grounding', 'guard_clarifying_limit', 'handoff_ai_requested', 'handoff_output_invalid', 'handoff_ai_unavailable', 'handoff_stale'));--> statement-breakpoint
ALTER TABLE "support_ai_jobs" ADD CONSTRAINT "support_ai_jobs_handoff_reason_check" CHECK (handoff_reason IS NULL OR handoff_reason IN ('SEND_OUTCOME_UNKNOWN', 'TRANSPORT_REFUSED', 'AI_REQUESTED', 'HANDOFF_TOPIC', 'HUMAN_REQUESTED', 'TOPIC_NOT_ALLOWED', 'LOW_CONFIDENCE', 'REPLY_OUT_OF_BOUNDS', 'DECISION_NOT_REPLY', 'AI_OUTPUT_INVALID', 'AI_UNAVAILABLE', 'ACCOUNT_UNDER_REVIEW', 'IDENTITY_UNVERIFIED', 'CUSTOMER_BLOCKED', 'INSUFFICIENT_GROUNDING', 'LOOP_GUARD', 'UNSUPPORTED_CONTENT', 'REPLY_STALE', 'CLARIFYING_LIMIT'));