ALTER TABLE "business_conversation_escalations" DROP CONSTRAINT "business_conversation_escalations_reason_check";--> statement-breakpoint
ALTER TABLE "business_conversations" DROP CONSTRAINT "business_conversations_handoff_reason_check";--> statement-breakpoint
ALTER TABLE "business_outbound_messages" DROP CONSTRAINT "business_outbound_messages_origin_check";--> statement-breakpoint
ALTER TABLE "business_outbound_messages" DROP CONSTRAINT "business_outbound_messages_author_check";--> statement-breakpoint
ALTER TABLE "support_ai_jobs" DROP CONSTRAINT "support_ai_jobs_outcome_check";--> statement-breakpoint
ALTER TABLE "support_ai_jobs" DROP CONSTRAINT "support_ai_jobs_handoff_reason_check";--> statement-breakpoint
ALTER TABLE "business_conversation_escalations" ADD COLUMN "topic" text;--> statement-breakpoint
ALTER TABLE "business_conversation_escalations" ADD COLUMN "intent" text;--> statement-breakpoint
ALTER TABLE "business_conversation_escalations" ADD COLUMN "steps_tried" integer;--> statement-breakpoint
ALTER TABLE "business_outbound_messages" ADD COLUMN "template_key" text;--> statement-breakpoint
ALTER TABLE "business_conversation_escalations" ADD CONSTRAINT "business_conversation_escalations_topic_check" CHECK (topic IN ('CONNECTION_TROUBLESHOOTING', 'APP_SETUP', 'SUBSCRIPTION_UPDATE', 'SERVICE_INFO', 'TRAFFIC_AND_EXPIRY', 'PLAN_INFO', 'KNOWN_ERROR', 'GREETING', 'REFUND', 'WALLET', 'PAYMENT_DISPUTE', 'PAYMENT_STATUS', 'RECEIPT_REVIEW', 'SERVICE_DELETE_OR_TERMINATE', 'OWNERSHIP_OR_ACCOUNT_TRANSFER', 'ACCOUNT_SECURITY', 'CREDENTIALS', 'PROVIDER_CHANGE', 'FRAUD_OR_CHARGEBACK', 'LEGAL_OR_SAFETY', 'HUMAN_REQUESTED', 'OTHER'));--> statement-breakpoint
ALTER TABLE "business_conversation_escalations" ADD CONSTRAINT "business_conversation_escalations_intent_check" CHECK (intent IS NULL OR length(intent) <= 600);--> statement-breakpoint
ALTER TABLE "business_conversation_escalations" ADD CONSTRAINT "business_conversation_escalations_steps_check" CHECK (steps_tried IS NULL OR steps_tried >= 0);--> statement-breakpoint
ALTER TABLE "business_conversation_escalations" ADD CONSTRAINT "business_conversation_escalations_reason_check" CHECK (reason IN ('SEND_OUTCOME_UNKNOWN', 'TRANSPORT_REFUSED', 'AI_REQUESTED', 'HANDOFF_TOPIC', 'HUMAN_REQUESTED', 'TOPIC_NOT_ALLOWED', 'LOW_CONFIDENCE', 'REPLY_OUT_OF_BOUNDS', 'DECISION_NOT_REPLY', 'AI_OUTPUT_INVALID', 'AI_UNAVAILABLE', 'ACCOUNT_UNDER_REVIEW', 'IDENTITY_UNVERIFIED', 'CUSTOMER_BLOCKED', 'INSUFFICIENT_GROUNDING', 'LOOP_GUARD', 'UNSUPPORTED_CONTENT', 'REPLY_STALE', 'CLARIFYING_LIMIT', 'NO_PROGRESS', 'REPEATED_ADVICE', 'INBOUND_FLOOD'));--> statement-breakpoint
ALTER TABLE "business_conversations" ADD CONSTRAINT "business_conversations_handoff_reason_check" CHECK (handoff_reason IN ('SEND_OUTCOME_UNKNOWN', 'TRANSPORT_REFUSED', 'AI_REQUESTED', 'HANDOFF_TOPIC', 'HUMAN_REQUESTED', 'TOPIC_NOT_ALLOWED', 'LOW_CONFIDENCE', 'REPLY_OUT_OF_BOUNDS', 'DECISION_NOT_REPLY', 'AI_OUTPUT_INVALID', 'AI_UNAVAILABLE', 'ACCOUNT_UNDER_REVIEW', 'IDENTITY_UNVERIFIED', 'CUSTOMER_BLOCKED', 'INSUFFICIENT_GROUNDING', 'LOOP_GUARD', 'UNSUPPORTED_CONTENT', 'REPLY_STALE', 'CLARIFYING_LIMIT', 'NO_PROGRESS', 'REPEATED_ADVICE', 'INBOUND_FLOOD'));--> statement-breakpoint
ALTER TABLE "business_outbound_messages" ADD CONSTRAINT "business_outbound_messages_template_check" CHECK ((origin = 'HANDOFF_NOTICE') = (template_key IS NOT NULL) AND (template_key IS NULL OR body IS NULL));--> statement-breakpoint
ALTER TABLE "business_outbound_messages" ADD CONSTRAINT "business_outbound_messages_origin_check" CHECK (origin IN ('OPERATOR', 'ASSIST', 'AUTO', 'HANDOFF_NOTICE'));--> statement-breakpoint
ALTER TABLE "business_outbound_messages" ADD CONSTRAINT "business_outbound_messages_author_check" CHECK ((origin IN ('AUTO', 'HANDOFF_NOTICE')) = (created_by_admin_id IS NULL));--> statement-breakpoint
ALTER TABLE "support_ai_jobs" ADD CONSTRAINT "support_ai_jobs_outcome_check" CHECK (outcome IS NULL OR outcome IN ('sent', 'sent_clarifying', 'dropped_mode', 'dropped_epoch', 'dropped_state', 'dropped_coalesced', 'dropped_connection', 'dropped_scope', 'guard_content', 'guard_customer_blocked', 'guard_consecutive', 'guard_window', 'guard_decision', 'guard_handoff_topic', 'guard_human_requested', 'guard_topic_allowlist', 'guard_identity', 'guard_account_review', 'guard_confidence', 'guard_reply_bounds', 'guard_grounding', 'guard_clarifying_limit', 'handoff_ai_requested', 'handoff_output_invalid', 'handoff_ai_unavailable', 'handoff_stale', 'guard_no_progress', 'guard_repeated_advice', 'guard_inbound_flood', 'no_action'));--> statement-breakpoint
ALTER TABLE "support_ai_jobs" ADD CONSTRAINT "support_ai_jobs_handoff_reason_check" CHECK (handoff_reason IS NULL OR handoff_reason IN ('SEND_OUTCOME_UNKNOWN', 'TRANSPORT_REFUSED', 'AI_REQUESTED', 'HANDOFF_TOPIC', 'HUMAN_REQUESTED', 'TOPIC_NOT_ALLOWED', 'LOW_CONFIDENCE', 'REPLY_OUT_OF_BOUNDS', 'DECISION_NOT_REPLY', 'AI_OUTPUT_INVALID', 'AI_UNAVAILABLE', 'ACCOUNT_UNDER_REVIEW', 'IDENTITY_UNVERIFIED', 'CUSTOMER_BLOCKED', 'INSUFFICIENT_GROUNDING', 'LOOP_GUARD', 'UNSUPPORTED_CONTENT', 'REPLY_STALE', 'CLARIFYING_LIMIT', 'NO_PROGRESS', 'REPEATED_ADVICE', 'INBOUND_FLOOD'));