import type { PermissionDomain, PermissionKey } from '@nexa/contracts';
import type { WebKey } from './i18n/web.fa';

/**
 * Persian names for the frozen permission catalogue (Phase D3).
 *
 * A `Record<PermissionKey, …>`, so adding a permission to the contract without naming it
 * here is a type error rather than a row the matrix renders as a bare key. The KEY stays
 * the identity everywhere; this is what an operator reads.
 *
 * That sentence was false until `PermissionKey` became the catalogue's literal union: it
 * was `string`, this was a `Record<string, …>`, and sixteen keys reached the contract
 * unnamed with only `tests/web/roles.test.tsx` to notice. `tests/web/permission-catalogue.typecheck.ts`
 * now pins both directions — a missing label and an unknown key fail to compile.
 */
export const PERMISSION_LABELS: Readonly<Record<PermissionKey, WebKey>> = {
  'users.view': 'web.perm_users_view',
  'users.search': 'web.perm_users_search',
  'users.edit': 'web.perm_users_edit',
  'users.block': 'web.perm_users_block',
  'users.trial.edit': 'web.perm_users_trial_edit',
  'users.channel_membership.exempt': 'web.perm_users_channel_membership_exempt',
  'users.phone.verify': 'web.perm_users_phone_verify',
  'users.location.edit': 'web.perm_users_location_edit',
  'users.notifications.edit': 'web.perm_users_notifications_edit',
  'users.transfer': 'web.perm_users_transfer',
  'users.tier.change': 'web.perm_users_tier_change',
  'users.wallet.credit': 'web.perm_users_wallet_credit',
  'users.wallet.credit.large': 'web.perm_users_wallet_credit_large',
  'users.wallet.debit': 'web.perm_users_wallet_debit',
  'users.wallet.mass': 'web.perm_users_wallet_mass',
  'orders.view': 'web.perm_orders_view',
  'orders.cancel': 'web.perm_orders_cancel',
  'orders.manual.create': 'web.perm_orders_manual_create',
  'payments.view': 'web.perm_payments_view',
  'payments.retry': 'web.perm_payments_retry',
  'payments.reconcile': 'web.perm_payments_reconcile',
  'payments.accounts.view': 'web.perm_payments_accounts_view',
  'payments.accounts.edit': 'web.perm_payments_accounts_edit',
  'payments.gateways.view': 'web.perm_payments_gateways_view',
  'payments.gateways.edit': 'web.perm_payments_gateways_edit',
  'receipts.view': 'web.perm_receipts_view',
  'receipts.review': 'web.perm_receipts_review',
  'refunds.view': 'web.perm_refunds_view',
  'refunds.issue': 'web.perm_refunds_issue',
  'services.view': 'web.perm_services_view',
  'services.edit': 'web.perm_services_edit',
  'services.terminate': 'web.perm_services_terminate',
  'services.transfer': 'web.perm_services_transfer',
  'catalog.view': 'web.perm_catalog_view',
  'catalog.edit': 'web.perm_catalog_edit',
  'catalog.pricing.edit': 'web.perm_catalog_pricing_edit',
  'catalog.discounts.edit': 'web.perm_catalog_discounts_edit',
  'panels.view': 'web.perm_panels_view',
  'panels.edit': 'web.perm_panels_edit',
  'panels.credentials.rotate': 'web.perm_panels_credentials_rotate',
  'panels.technical.view': 'web.perm_panels_technical_view',
  'referrals.view': 'web.perm_referrals_view',
  'resellers.view': 'web.perm_resellers_view',
  'resellers.edit': 'web.perm_resellers_edit',
  'settings.view': 'web.perm_settings_view',
  'settings.edit': 'web.perm_settings_edit',
  'settings.destructive': 'web.perm_settings_destructive',
  'templates.view': 'web.perm_templates_view',
  'templates.edit': 'web.perm_templates_edit',
  'client_apps.view': 'web.perm_client_apps_view',
  'client_apps.edit': 'web.perm_client_apps_edit',
  'admins.view': 'web.perm_admins_view',
  'admins.edit': 'web.perm_admins_edit',
  'admins.permissions.edit': 'web.perm_admins_permissions_edit',
  'broadcasts.send': 'web.perm_broadcasts_send',
  'broadcasts.view': 'web.perm_broadcasts_view',
  'services.mass.grant': 'web.perm_services_mass_grant',
  'bulk_operations.view': 'web.perm_bulk_operations_view',
  'tickets.view': 'web.perm_tickets_view',
  'business_chats.view': 'web.perm_business_chats_view',
  'business_chats.reply': 'web.perm_business_chats_reply',
  'support_ai.configure': 'web.perm_support_ai_configure',
  'support_ai.auto_reply': 'web.perm_support_ai_auto_reply',
  'support_ai.assist': 'web.perm_support_ai_assist',
  'support_knowledge.view': 'web.perm_support_knowledge_view',
  'support_knowledge.propose': 'web.perm_support_knowledge_propose',
  'support_knowledge.review': 'web.perm_support_knowledge_review',
  'legacy.products.view': 'web.perm_legacy_products_view',
  'legacy.products.decide': 'web.perm_legacy_products_decide',
  'legacy.invoices.view': 'web.perm_legacy_invoices_view',
  'legacy.invoices.pii.view': 'web.perm_legacy_invoices_pii_view',
  'tickets.reply': 'web.perm_tickets_reply',
  'tickets.assign': 'web.perm_tickets_assign',
  'tickets.close': 'web.perm_tickets_close',
  'tickets.categories.edit': 'web.perm_tickets_categories_edit',
  'campaigns.view': 'web.perm_campaigns_view',
  'campaigns.manage': 'web.perm_campaigns_manage',
  'reports.view': 'web.perm_reports_view',
  'reports.pii.view': 'web.perm_reports_pii_view',
  'reports.export': 'web.perm_reports_export',
  'audit.view': 'web.perm_audit_view',
  'opslog.view': 'web.perm_opslog_view',
  'backup.view': 'web.perm_backup_view',
  'backup.run': 'web.perm_backup_run',
  'backup.download': 'web.perm_backup_download',
  'recovery.restore': 'web.perm_recovery_restore',
  'recovery.kit.export': 'web.perm_recovery_kit_export',
  'recovery.kit.import': 'web.perm_recovery_kit_import',
  'recovery.key.remove': 'web.perm_recovery_key_remove',
  'tenant.cross_read': 'web.perm_tenant_cross_read',
  'maintenance.run': 'web.perm_maintenance_run',
  'users.message.send': 'web.perm_users_message_send',
  'users.message.view': 'web.perm_users_message_view',
  'users.notes.view': 'web.perm_users_notes_view',
  'users.notes.write': 'web.perm_users_notes_write',
  'users.tags.assign': 'web.perm_users_tags_assign',
  'users.tags.manage': 'web.perm_users_tags_manage',
  'terms.view': 'web.perm_terms_view',
  'terms.edit': 'web.perm_terms_edit',
  'terms.publish': 'web.perm_terms_publish',
  'audit.export': 'web.perm_audit_export',
  'panels.drain': 'web.perm_panels_drain',
  'services.grant': 'web.perm_services_grant',
  'services.mass.status': 'web.perm_services_mass_status',
  // Phase E3: incidents and maintenance.
  'incidents.view': 'web.perm_incidents_view',
  'incidents.manage': 'web.perm_incidents_manage',
  'incidents.notify': 'web.perm_incidents_notify',
};

/**
 * Persian names for the catalogue's domains (a permission's `resource`). Total over
 * `PermissionDomain`, which is derived from the catalogue: a permission in a new domain
 * without a name here is a compile error, and so is a name for a domain that does not exist.
 */
export const PERMISSION_DOMAIN_LABELS: Readonly<Record<PermissionDomain, WebKey>> = {
  users: 'web.perm_domain_users',
  orders: 'web.perm_domain_orders',
  payments: 'web.perm_domain_payments',
  receipts: 'web.perm_domain_receipts',
  refunds: 'web.perm_domain_refunds',
  services: 'web.perm_domain_services',
  catalog: 'web.perm_domain_catalog',
  panels: 'web.perm_domain_panels',
  referrals: 'web.perm_domain_referrals',
  resellers: 'web.perm_domain_resellers',
  settings: 'web.perm_domain_settings',
  templates: 'web.perm_domain_templates',
  client_apps: 'web.perm_domain_client_apps',
  admins: 'web.perm_domain_admins',
  broadcasts: 'web.perm_domain_broadcasts',
  bulk_operations: 'web.perm_domain_bulk_operations',
  tickets: 'web.perm_domain_tickets',
  business_chats: 'web.perm_domain_business_chats',
  support_ai: 'web.perm_domain_support_ai',
  support_knowledge: 'web.perm_domain_support_knowledge',
  campaigns: 'web.perm_domain_campaigns',
  reports: 'web.perm_domain_reports',
  audit: 'web.perm_domain_audit',
  opslog: 'web.perm_domain_opslog',
  backup: 'web.perm_domain_backup',
  recovery: 'web.perm_domain_recovery',
  tenant: 'web.perm_domain_tenant',
  maintenance: 'web.perm_domain_maintenance',
  legacy: 'web.perm_domain_legacy',
  terms: 'web.perm_domain_terms',
  incidents: 'web.perm_domain_incidents',
};
