-- SYNTHETIC legacy fixture v1 (not evidence)
-- Generated by tests/fixtures/legacy/synthetic-legacy.ts. NOT EVIDENCE.
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `id` varchar(500) NOT NULL PRIMARY KEY,
  `limit_usertest` varchar(32) NULL,
  `Balance` varchar(64) NULL,
  `number` varchar(2000) NULL,
  `User_Status` varchar(500) NULL,
  `agent` varchar(100) NULL,
  `affiliates` varchar(100) NULL,
  `username` varchar(1000) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
INSERT INTO `user` (`id`, `limit_usertest`, `Balance`, `number`, `User_Status`, `agent`, `affiliates`, `username`) VALUES ('100000001', '1', '50000', '989121234567', 'Active', 'f', '0', 'alice_legacy');
INSERT INTO `user` (`id`, `limit_usertest`, `Balance`, `number`, `User_Status`, `agent`, `affiliates`, `username`) VALUES ('100000002', '1', '0', 'none', 'Active', 'f', '0', 'none');
INSERT INTO `user` (`id`, `limit_usertest`, `Balance`, `number`, `User_Status`, `agent`, `affiliates`, `username`) VALUES ('100000003', '0', '-20000', 'none', 'Active', 'f', '0', 'none');
INSERT INTO `user` (`id`, `limit_usertest`, `Balance`, `number`, `User_Status`, `agent`, `affiliates`, `username`) VALUES ('100000004', '1', '12.5', 'none', 'Active', 'f', '0', 'none');
INSERT INTO `user` (`id`, `limit_usertest`, `Balance`, `number`, `User_Status`, `agent`, `affiliates`, `username`) VALUES ('100000005', '1', '30000', 'call me', 'Active', 'f', '0', 'none');
INSERT INTO `user` (`id`, `limit_usertest`, `Balance`, `number`, `User_Status`, `agent`, `affiliates`, `username`) VALUES ('not-a-telegram-id', '1', '100', 'none', 'Active', 'f', '0', 'none');
INSERT INTO `user` (`id`, `limit_usertest`, `Balance`, `number`, `User_Status`, `agent`, `affiliates`, `username`) VALUES ('100000007', 'x', '1000', 'none', 'Active', 'n', '0', 'none');
INSERT INTO `user` (`id`, `limit_usertest`, `Balance`, `number`, `User_Status`, `agent`, `affiliates`, `username`) VALUES ('100000008', '1', '99999999999999', 'none', 'Active', 'f', '0', 'none');
INSERT INTO `user` (`id`, `limit_usertest`, `Balance`, `number`, `User_Status`, `agent`, `affiliates`, `username`) VALUES ('100000009', '9', '0', '12', 'Active', 'n2', '0', 'none');
INSERT INTO `user` (`id`, `limit_usertest`, `Balance`, `number`, `User_Status`, `agent`, `affiliates`, `username`) VALUES ('100000010', '1', '7000', 'none', 'Active', 'f', '0', 'none');
INSERT INTO `user` (`id`, `limit_usertest`, `Balance`, `number`, `User_Status`, `agent`, `affiliates`, `username`) VALUES ('100000011', '1', '12345', 'none', 'Active', 'f', '0', 'none');
DROP TABLE IF EXISTS `invoice`;
CREATE TABLE `invoice` (
  `id_invoice` varchar(200) NOT NULL PRIMARY KEY,
  `id_user` varchar(200) NULL,
  `username` varchar(200) NULL,
  `Service_location` varchar(200) NULL,
  `time_sell` varchar(200) NULL,
  `name_product` varchar(200) NULL,
  `price_product` varchar(200) NULL,
  `Volume` varchar(200) NULL,
  `Service_time` varchar(200) NULL,
  `Status` varchar(200) NULL,
  `code_panel` varchar(200) NULL,
  `code_product` varchar(200) NULL,
  `is_test` varchar(10) NULL,
  `is_custom` varchar(10) NULL,
  `time_unit` varchar(50) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
INSERT INTO `invoice` (`id_invoice`, `id_user`, `username`, `Service_location`, `time_sell`, `name_product`, `price_product`, `Volume`, `Service_time`, `Status`, `code_panel`, `code_product`, `is_test`, `is_custom`, `time_unit`) VALUES ('a0000001', '100000001', 'svc_a1', 'synthetic', '1700000000', 'synthetic', '150000', '30', '30', 'active', 'rp1', NULL, '0', '0', '');
INSERT INTO `invoice` (`id_invoice`, `id_user`, `username`, `Service_location`, `time_sell`, `name_product`, `price_product`, `Volume`, `Service_time`, `Status`, `code_panel`, `code_product`, `is_test`, `is_custom`, `time_unit`) VALUES ('7c1f', '100000001', 'svc_missing', 'synthetic', '1700000000', 'synthetic', '150000', '30', '30', 'active', 'rp1', NULL, '0', '0', '');
INSERT INTO `invoice` (`id_invoice`, `id_user`, `username`, `Service_location`, `time_sell`, `name_product`, `price_product`, `Volume`, `Service_time`, `Status`, `code_panel`, `code_product`, `is_test`, `is_custom`, `time_unit`) VALUES ('1700001b2c3d4e5', '100000002', 'svc_nullmatch', 'synthetic', '1700000000', 'synthetic', '150000', '30', '30', 'active', NULL, NULL, '0', '0', '');
INSERT INTO `invoice` (`id_invoice`, `id_user`, `username`, `Service_location`, `time_sell`, `name_product`, `price_product`, `Volume`, `Service_time`, `Status`, `code_panel`, `code_product`, `is_test`, `is_custom`, `time_unit`) VALUES ('a0000004', '100000003', 'svc_shared', 'synthetic', '1700000000', 'synthetic', '150000', '30', '30', 'active', NULL, NULL, '0', '0', '');
INSERT INTO `invoice` (`id_invoice`, `id_user`, `username`, `Service_location`, `time_sell`, `name_product`, `price_product`, `Volume`, `Service_time`, `Status`, `code_panel`, `code_product`, `is_test`, `is_custom`, `time_unit`) VALUES ('a0000005', '100000003', 'svc_nowhere', 'synthetic', '1700000000', 'synthetic', '150000', '30', '30', 'active', '', NULL, '0', '0', '');
INSERT INTO `invoice` (`id_invoice`, `id_user`, `username`, `Service_location`, `time_sell`, `name_product`, `price_product`, `Volume`, `Service_time`, `Status`, `code_panel`, `code_product`, `is_test`, `is_custom`, `time_unit`) VALUES ('a0000006', '100000005', 'whatever', 'synthetic', '1700000000', 'synthetic', '150000', '30', '30', 'active', 'tst', NULL, '0', '0', '');
INSERT INTO `invoice` (`id_invoice`, `id_user`, `username`, `Service_location`, `time_sell`, `name_product`, `price_product`, `Volume`, `Service_time`, `Status`, `code_panel`, `code_product`, `is_test`, `is_custom`, `time_unit`) VALUES ('a0000007', '100000005', 'svc_a1', 'synthetic', '1700000000', 'synthetic', '150000', '30', '30', 'active', 'zzz', NULL, '0', '0', '');
INSERT INTO `invoice` (`id_invoice`, `id_user`, `username`, `Service_location`, `time_sell`, `name_product`, `price_product`, `Volume`, `Service_time`, `Status`, `code_panel`, `code_product`, `is_test`, `is_custom`, `time_unit`) VALUES ('a0000008', '100000007', 'case_x', 'synthetic', '1700000000', 'synthetic', '150000', '30', '30', 'active', 'rp1', NULL, '0', '0', '');
INSERT INTO `invoice` (`id_invoice`, `id_user`, `username`, `Service_location`, `time_sell`, `name_product`, `price_product`, `Volume`, `Service_time`, `Status`, `code_panel`, `code_product`, `is_test`, `is_custom`, `time_unit`) VALUES ('a0000009', '100000009', 'svc_b1', 'synthetic', '1700000000', 'synthetic', '150000', '15', '45', 'active', 'rp2', NULL, '0', '1', '');
INSERT INTO `invoice` (`id_invoice`, `id_user`, `username`, `Service_location`, `time_sell`, `name_product`, `price_product`, `Volume`, `Service_time`, `Status`, `code_panel`, `code_product`, `is_test`, `is_custom`, `time_unit`) VALUES ('a000000a', '100000009', 'svc_b2', 'synthetic', '1700000000', 'synthetic', '150000', '30', '30', 'active', 'rp2', NULL, '0', '0', 'month');
INSERT INTO `invoice` (`id_invoice`, `id_user`, `username`, `Service_location`, `time_sell`, `name_product`, `price_product`, `Volume`, `Service_time`, `Status`, `code_panel`, `code_product`, `is_test`, `is_custom`, `time_unit`) VALUES ('a000000b', '999999999', 'svc_a1', 'synthetic', '1700000000', 'synthetic', '150000', '30', '30', 'active', 'rp1', NULL, '0', '0', '');
INSERT INTO `invoice` (`id_invoice`, `id_user`, `username`, `Service_location`, `time_sell`, `name_product`, `price_product`, `Volume`, `Service_time`, `Status`, `code_panel`, `code_product`, `is_test`, `is_custom`, `time_unit`) VALUES ('a000000c', '100000004', 'svc_a1', 'synthetic', '1700000000', 'synthetic', '150000', '30', '30', 'active', 'rp1', NULL, '0', '0', '');
INSERT INTO `invoice` (`id_invoice`, `id_user`, `username`, `Service_location`, `time_sell`, `name_product`, `price_product`, `Volume`, `Service_time`, `Status`, `code_panel`, `code_product`, `is_test`, `is_custom`, `time_unit`) VALUES ('a000000d', '100000002', 'svc_test', 'synthetic', '1700000000', 'synthetic', '150000', '30', '30', 'active', 'rp1', NULL, '1', '0', '');
INSERT INTO `invoice` (`id_invoice`, `id_user`, `username`, `Service_location`, `time_sell`, `name_product`, `price_product`, `Volume`, `Service_time`, `Status`, `code_panel`, `code_product`, `is_test`, `is_custom`, `time_unit`) VALUES ('a000000e', '100000001', 'svc_a1', 'synthetic', '1700000000', 'synthetic', '150000', '30', '30', 'active', 'rp1', NULL, 'x', '0', '');
INSERT INTO `invoice` (`id_invoice`, `id_user`, `username`, `Service_location`, `time_sell`, `name_product`, `price_product`, `Volume`, `Service_time`, `Status`, `code_panel`, `code_product`, `is_test`, `is_custom`, `time_unit`) VALUES ('a000000f', '100000001', 'svc_a2', 'synthetic', '1700000000', 'synthetic', '150000', '30', '30', 'active', 'rp1', 'p1', '0', '0', '');
INSERT INTO `invoice` (`id_invoice`, `id_user`, `username`, `Service_location`, `time_sell`, `name_product`, `price_product`, `Volume`, `Service_time`, `Status`, `code_panel`, `code_product`, `is_test`, `is_custom`, `time_unit`) VALUES ('a0000010', '100000001', 'svc_a3', 'synthetic', '1700000000', 'synthetic', '150000', '30', '30', 'active', 'gone', NULL, '0', '0', '');
INSERT INTO `invoice` (`id_invoice`, `id_user`, `username`, `Service_location`, `time_sell`, `name_product`, `price_product`, `Volume`, `Service_time`, `Status`, `code_panel`, `code_product`, `is_test`, `is_custom`, `time_unit`) VALUES ('a0000011', '100000001', 'svc_a4', 'synthetic', '1700000000', 'synthetic', '150000', '0', '30', 'active', 'rp1', NULL, '0', '0', '');
INSERT INTO `invoice` (`id_invoice`, `id_user`, `username`, `Service_location`, `time_sell`, `name_product`, `price_product`, `Volume`, `Service_time`, `Status`, `code_panel`, `code_product`, `is_test`, `is_custom`, `time_unit`) VALUES ('a0000012', '100000001', '', 'synthetic', '1700000000', 'synthetic', '150000', '30', '30', 'active', 'rp1', NULL, '0', '0', '');
INSERT INTO `invoice` (`id_invoice`, `id_user`, `username`, `Service_location`, `time_sell`, `name_product`, `price_product`, `Volume`, `Service_time`, `Status`, `code_panel`, `code_product`, `is_test`, `is_custom`, `time_unit`) VALUES ('LEGACY-X1', '100000001', 'svc_a1', 'synthetic', '1700000000', 'synthetic', '150000', '30', '30', 'active', 'rp1', NULL, '0', '0', '');
INSERT INTO `invoice` (`id_invoice`, `id_user`, `username`, `Service_location`, `time_sell`, `name_product`, `price_product`, `Volume`, `Service_time`, `Status`, `code_panel`, `code_product`, `is_test`, `is_custom`, `time_unit`) VALUES ('a0000014', '100000003', 'svc_old', 'synthetic', '1700000000', 'synthetic', '150000', '30', '30', 'removed', 'rp1', NULL, '0', '0', '');
INSERT INTO `invoice` (`id_invoice`, `id_user`, `username`, `Service_location`, `time_sell`, `name_product`, `price_product`, `Volume`, `Service_time`, `Status`, `code_panel`, `code_product`, `is_test`, `is_custom`, `time_unit`) VALUES ('a0000015', '100000010', 'svc_oldtest', 'synthetic', '1700000000', 'synthetic', '150000', '30', '30', 'removed', 'rp1', NULL, '1', '0', '');
DROP TABLE IF EXISTS `product`;
CREATE TABLE `product` (
  `id` int(6) unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `code_product` varchar(200) NULL,
  `name_product` varchar(2000) NULL,
  `price_product` varchar(2000) NULL,
  `Volume_constraint` varchar(2000) NULL,
  `Service_time` varchar(200) NULL,
  `agent` varchar(100) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
INSERT INTO `product` (`id`, `code_product`, `name_product`, `price_product`, `Volume_constraint`, `Service_time`, `agent`) VALUES ('1', 'p1', 'synthetic 30GB', '150000', '30', '30', 'f');
INSERT INTO `product` (`id`, `code_product`, `name_product`, `price_product`, `Volume_constraint`, `Service_time`, `agent`) VALUES ('2', 'p2', 'synthetic agent plan', '120000', '50', '30', 'n');
DROP TABLE IF EXISTS `nexa_synthetic_unclassified`;
CREATE TABLE `nexa_synthetic_unclassified` (
  `id` int(10) unsigned NOT NULL PRIMARY KEY,
  `note` varchar(200) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
INSERT INTO `nexa_synthetic_unclassified` (`id`, `note`) VALUES ('1', 'synthetic');
INSERT INTO `nexa_synthetic_unclassified` (`id`, `note`) VALUES ('2', NULL);
INSERT INTO `nexa_synthetic_unclassified` (`id`, `note`) VALUES ('10', 'synthetic');
DROP TABLE IF EXISTS `nexa_synthetic_fixture`;
CREATE TABLE `nexa_synthetic_fixture` (`label` varchar(200) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
INSERT INTO `nexa_synthetic_fixture` (`label`) VALUES ('SYNTHETIC legacy fixture v1 (not evidence)');
