import { Controller, Get, Inject, Param, Query, Res } from '@nestjs/common';
import type { FastifyReply } from 'fastify';
import { z } from 'zod';
import {
  COMMERCE_ERROR_CODES,
  GATEWAY_RETURN_PATH_PREFIX,
  PAYMENT_GATEWAY_DESCRIPTORS,
  PAYMENT_GATEWAY_PROVIDERS,
  errors,
  type PaymentGatewayProvider,
} from '@nexa/contracts';
import { CONTAINER, type Container } from '../../container.js';

const tenantIdSchema = z.uuid();

/**
 * A customer's browser coming back from a provider's payment page (CentralPay,
 * `docs/centralpay-gateway-audit.md` §5.6).
 *
 * `GET /payments/return/<provider>/<tenantId>?orderId=<n>`. The URL is GENERATED by this
 * installation and sent with each `getLink`; the provider's guide requires the order id in
 * it because the return is a GET that carries no payment data.
 *
 * ## A browser return is not proof of anything
 *
 * Anyone can open this URL with any order id. So it moves no money and decides nothing: the
 * service locates the attempt inside the tenant the URL names and, for an OPEN one, brings
 * the next server-to-server verify forward — the worker makes that call under the tenant's
 * budget, and only its answer can reach the settlement path. An attempt already decided is
 * answered from its local state; nothing is asked again, so a refreshed or replayed return
 * can never verify, settle or credit twice. No settlement happens in this controller.
 *
 * ## What the browser sees
 *
 * The codebase serves no public pages, so the browser is redirected (302) back to the
 * tenant's bot, `https://t.me/<username>`, where the customer's payment message is edited in
 * place once the verify has answered. The answer is the same whether or not the attempt
 * exists. With no bot to name, `{ ok: true }`.
 */
@Controller()
export class GatewayReturnController {
  constructor(@Inject(CONTAINER) private readonly container: Container) {}

  @Get(`${GATEWAY_RETURN_PATH_PREFIX}/:provider/:tenantId`)
  async receive(
    @Param('provider') providerParam: string,
    @Param('tenantId') tenantIdParam: string,
    @Query('orderId') orderId: unknown,
    @Res() reply: FastifyReply,
  ): Promise<void> {
    const provider = browserReturnProviderOf(providerParam);
    if (provider === null) {
      throw errors.notFound(COMMERCE_ERROR_CODES.PAYMENT_GATEWAY_NOT_FOUND, 'Unknown route.');
    }
    const tenant = tenantIdSchema.safeParse(tenantIdParam);
    const result = tenant.success
      ? await this.container.gatewayPayments.receiveBrowserReturn(
          tenant.data,
          provider,
          typeof orderId === 'string' ? orderId : undefined,
        )
      : { state: 'UNKNOWN' as const, botLink: null };
    // Never cached: a later return must reach the service again.
    void reply.header('cache-control', 'no-store');
    if (result.botLink !== null) {
      await reply.redirect(result.botLink, 302);
      return;
    }
    await reply.status(200).send({ ok: true });
  }
}

/** The provider an URL segment names, if it is a BROWSER-RETURN route of the closed catalogue. */
function browserReturnProviderOf(segment: string): PaymentGatewayProvider | null {
  const found = PAYMENT_GATEWAY_PROVIDERS.find((provider) => provider.toLowerCase() === segment);
  if (found === undefined) return null;
  return PAYMENT_GATEWAY_DESCRIPTORS[found].browserReturn ? found : null;
}
