import { Body, Controller, Headers, HttpCode, Inject, Param, Post } from '@nestjs/common';
import { z } from 'zod';
import {
  COMMERCE_ERROR_CODES,
  PAYMENT_GATEWAY_DESCRIPTORS,
  PAYMENT_GATEWAY_PROVIDERS,
  TONPAYS_DELIVERY_ID_HEADER,
  errors,
  type PaymentGatewayProvider,
} from '@nexa/contracts';
import { CONTAINER, type Container } from '../../container.js';
import { GATEWAY_WEBHOOK_PATH_PREFIX } from '../../modules/commerce/payments/application/gateway-payment.service.js';

/**
 * The largest body a gateway webhook may carry. The documented TonPays body is a few
 * hundred bytes; an unauthenticated route reads no more than it must.
 */
export const GATEWAY_WEBHOOK_BODY_LIMIT_BYTES = 16 * 1024;

/** The route prefix the limit above is applied to, matched by an `onRoute` hook. */
export const GATEWAY_WEBHOOK_ROUTE_PREFIX = GATEWAY_WEBHOOK_PATH_PREFIX;

const tenantIdSchema = z.uuid();

/**
 * External payment gateway webhooks (WP11A, `docs/tonpays-gateway-audit.md` §5.6).
 *
 * `POST /payments/webhook/<provider>/<tenantId>`. The URL is GENERATED by this
 * installation and sent with each invoice; nobody types it.
 *
 * ## A webhook is a hint, never evidence
 *
 * TonPays documents an `X-TonPays-Signature` header and does not document how to verify
 * it, so it is not verified, not read and not logged — and neither is the `X-API-Key`
 * header the provider sends. Nothing a webhook says can settle a payment: it locates the
 * attempt inside the tenant the URL names, deduplicates on the delivery id, records what
 * it hinted and brings the next server-to-server INQUIRY forward. Only that inquiry's
 * answer reaches the settlement path, in the worker.
 *
 * ## The answer does not depend on what exists
 *
 * A well-formed body is answered `{ ok: true }` whether the tenant exists, the attempt
 * exists, the ids match or the delivery is a duplicate — so the endpoint says nothing
 * about which tenants or orders exist, and a provider retrying an unknown id is not
 * encouraged to retry for ever. A body that is not the documented shape is a 400, like
 * every other malformed command here; the provider is not the sender of such a body.
 *
 * No external call is made here, and no money moves here.
 */
@Controller()
export class GatewayWebhookController {
  constructor(@Inject(CONTAINER) private readonly container: Container) {}

  @Post(`${GATEWAY_WEBHOOK_PATH_PREFIX}/:provider/:tenantId`)
  @HttpCode(200)
  async receive(
    @Param('provider') providerParam: string,
    @Param('tenantId') tenantIdParam: string,
    @Headers(TONPAYS_DELIVERY_ID_HEADER) deliveryId: string | undefined,
    @Body() body: unknown,
  ): Promise<{ ok: true }> {
    const provider = externalProviderOf(providerParam);
    if (provider === null) {
      throw errors.notFound(COMMERCE_ERROR_CODES.PAYMENT_GATEWAY_NOT_FOUND, 'Unknown route.');
    }
    const tenant = tenantIdSchema.safeParse(tenantIdParam);
    if (!tenant.success) return { ok: true };

    const result = await this.container.gatewayPayments.receiveWebhook(
      tenant.data,
      provider,
      body,
      deliveryId,
    );
    if (result === 'MALFORMED') {
      throw errors.validation(
        COMMERCE_ERROR_CODES.COMMERCE_REQUEST_INVALID,
        'That is not a payment gateway notification.',
      );
    }
    return { ok: true };
  }
}

/** The provider an URL segment names, if it is an EXTERNAL route of the closed catalogue. */
function externalProviderOf(segment: string): PaymentGatewayProvider | null {
  const found = PAYMENT_GATEWAY_PROVIDERS.find((provider) => provider.toLowerCase() === segment);
  if (found === undefined) return null;
  return PAYMENT_GATEWAY_DESCRIPTORS[found].settlesVia === 'GATEWAY' ? found : null;
}
