import { createServer, type IncomingMessage, type Server, type ServerResponse } from 'node:http';
import { once } from 'node:events';
import type { AddressInfo } from 'node:net';

/**
 * A deterministic RickPanel, on a real socket.
 *
 * Built from two sources, and it says which is which:
 *
 *   - `rickpanel-openapi.json`, the per-admin document the owner attached. Its
 *     descriptions are the contract (`docs/rickpanel-adapter-audit.md` §1): a
 *     form-encoded token exchange, a 400 "saying which rule was hit", a 409 for a
 *     name in use, and a create that "returns before the nodes have the user".
 *   - the owner's direct calls to a correctly connected panel
 *     (`docs/rickpanel-create-hotfix.md` §2). They are where this fake refuses a
 *     create with no `proxies`, where an accepted create comes back holding a
 *     credential for SEVERAL protocols, an active status, a `subscription_url` and a
 *     `sub_token`, and where `revoke_sub` answers 200 and changes the token and
 *     nothing else.
 *
 * One thing in here is NOT evidence and is marked as such: the status a real panel
 * answers an unseeded create with has not been captured (`OQ-RP-06`). It is a
 * setting, so a test can name the status it depends on.
 *
 * Real sockets and the real `SafeHttpClient` against them, for the reason the other
 * two fakes use them: mocking the client away erases URL composition and whether a
 * credential can escape to another origin.
 */

export type RickpanelBehaviour =
  /** Answers as the owner's panel did. */
  | 'healthy'
  /** Every create answers 400 — a rule was hit: a user limit, a service rule. */
  | 'refuses-rule'
  /** Every create answers 422. What a real panel means by one is `OQ-RP-06`. */
  | 'unprocessable'
  /** Every create answers 500 without creating anything. */
  | 'server-error';

/**
 * What `POST /api/user/{username}/revoke_sub` does.
 *
 * `rotates` is the owner's measurement (`docs/rickpanel-rotate-audit.md` §2): a 200, and
 * afterwards a new token and a new link with nothing else changed. The others are the
 * shapes the adapter's read-back exists for, and none is evidence about a real panel.
 */
export type RickpanelRevokeMode =
  | 'rotates'
  /** The rotation takes effect and the answer is lost: a 500 after the write. */
  | 'rotates-then-500'
  /** The rotation takes effect and the connection drops without an answer. */
  | 'rotates-then-drops'
  /** A 500 and no rotation. */
  | 'fails-500'
  /** A 200 that changes nothing. */
  | 'no-op-200';

/**
 * How `GET /api/users` pages (Migration P5).
 *
 * NOT EVIDENCE about RickPanel (`OQ-P5-01`). `documented` is Marzban v0.8.4's documented
 * list route — `?offset=&limit=`, answering `{"users": [...], "total": N}` — which a
 * Marzban-derived panel is inferred to share. The other modes are the ways a panel could
 * page badly, each of which the inventory must refuse or survive:
 */
export type RickpanelListMode =
  | 'documented'
  /** Returns the first page whatever `offset` says: a loop that never ends. */
  | 'ignores-offset'
  /** Returns everything from `offset` whatever `limit` says. */
  | 'ignores-limit'
  /** Caps every page at `listPageCap` rows, below what was asked. */
  | 'caps-page-size'
  /** A bare JSON array instead of the page object. */
  | 'bare-array'
  /** The page object without `total`. */
  | 'no-total';

export interface FakeRickpanelOptions {
  readonly username?: string;
  readonly password?: string;
  readonly behaviour?: RickpanelBehaviour;
  readonly host?: string;
  /** The status for a create whose `proxies` is missing or empty. Unmeasured: `OQ-RP-06`. */
  readonly missingSeedStatus?: number;
}

export interface FakeRickpanelUser {
  readonly username: string;
  status: string;
  /** Epoch SECONDS; 0 is the panel's "never". */
  expire: number;
  /** Bytes; 0 is the panel's "unlimited". */
  dataLimit: number;
  usedTraffic: number;
  /** Generated by the panel, per protocol. Never a thing a customer should see. */
  readonly proxies: Readonly<Record<string, Readonly<Record<string, string>>>>;
  /** Replaced by `revoke_sub`. */
  subToken: string;
}

export interface FakeRickpanelRequest {
  readonly method: string;
  readonly path: string;
  readonly body: string;
}

export interface FakeRickpanel {
  readonly baseUrl: string;
  readonly username: string;
  readonly password: string;
  behaviour: RickpanelBehaviour;
  /**
   * How many of the NEXT creates answer 422 before the panel behaves as `behaviour`
   * says. A panel that recovers between two attempts, which is the case a reconcile
   * exists for.
   */
  unprocessableCreates: number;
  /** What the next `revoke_sub` does. */
  revokeMode: RickpanelRevokeMode;
  /**
   * Run after a `rotates` revoke has changed the token and before it answers: a hook
   * for a test to change the world while the rotation is on the wire.
   */
  afterRotation: (() => Promise<void>) | null;
  /** How many of the NEXT `PUT /api/user/{name}` apply their change and then answer 500. */
  lostPutAnswers: number;
  /** How many `PUT /api/user/{name}` calls reached the panel, whatever they did. */
  putCalls(): number;
  /**
   * How many of the NEXT `GET /api/user/{name}` answer 429 without reading anything
   * (WP15 H1): the read after an accepted create, lost to a rate limit.
   */
  rateLimitedReads: number;
  /**
   * WP15 G3: the next N reads of a user answer 404 even though the panel holds it — the
   * propagation window after an accepted create.
   */
  hiddenReads: number;
  /** WP15 G7: the next N reads of a user drop the connection before answering. */
  droppedReads: number;
  /** WP15 G2: the next N modifies answer 500 WITHOUT applying anything. */
  unappliedPutFailures: number;
  /** WP15 G5: numeric fields spelled as strings, the way the document's schema types them. */
  stringNumbers: boolean;
  /** WP15 G5: a record with no `used_traffic` at all. */
  omitUsedTraffic: boolean;
  readonly requests: readonly FakeRickpanelRequest[];
  /** Everything this panel holds, keyed by username — the observer's view. */
  readonly users: ReadonlyMap<string, FakeRickpanelUser>;
  /** How many creates reached the panel, accepted or not. */
  createCalls(): number;
  /** How many `revoke_sub` calls reached the panel, whatever they did. */
  revokeCalls(): number;
  /** Migration P5: how `GET /api/users` pages. */
  listMode: RickpanelListMode;
  /** The row cap for `caps-page-size`. */
  listPageCap: number;
  /** Run before each list page is answered: a hook to change the panel mid-walk. */
  beforeListPage: ((offset: number) => void) | null;
  /** How many `GET /api/users` reached the panel. */
  listCalls(): number;
  /** Put an account on the panel directly, as an operator's own panel would hold it. */
  seedUser(name: string, fields?: Partial<Omit<FakeRickpanelUser, 'username'>>): void;
  /**
   * Package E: the body `GET /api/user/{name}/files` answers with, or null for the
   * panel's own — one JSON config and one plain-text list per user, both built from the
   * user's subscription token, which is how a test can prove the bytes were never kept.
   */
  filesBody: string | null;
  /**
   * Package E: the panel's documented limit, "once a minute per user", enforced: a
   * second content read inside the window answers 429 with `Retry-After` in seconds.
   * Zero turns it off.
   */
  filesWindowMs: number;
  /** How many content reads of `/files` reached the panel, limited or not. */
  filesCalls(): number;
  /**
   * C3: what the public `GET /sub/{username}/{token}` route does — serve the user's
   * subscription (`serves`), answer 200 with nothing (`empty`), or 404 (`missing`). A
   * served read stamps the user's `sub_updated_at`, as a Marzban-lineage panel records a
   * client's fetch.
   */
  subscriptionMode: 'serves' | 'empty' | 'missing' | 'html';
  /** C3: user records carry no `subscription_url` and no `sub_token`. */
  omitSubscriptionLink: boolean;
  /** C3: the `content-type` a served subscription answers with. */
  subscriptionContentType: string;
  /**
   * C3: fields merged over the record `GET /api/user/{name}` answers with (and only
   * that route) — a wrong `username`, an absolute `subscription_url`, a field the
   * documented modify carries. Mutable between two reads.
   */
  readonly userReadExtras: Record<string, unknown>;
  /** How many `GET /sub/...` reached the panel. */
  subscriptionReads(): number;
  /**
   * R3: forgets every `/files` read so far — the rate window and the count — as a minute
   * passing would. Since R3 the delivery lane reads the files right after provisioning,
   * so a test that exercises the customer's own tap starts from here.
   */
  forgetFileReads(): void;
  close(): Promise<void>;
}

/** The two formats the fake builds for a user, from its token (Package E). */
export function fakeRickpanelFiles(user: FakeRickpanelUser): readonly {
  readonly filename: string;
  readonly media_type: string;
  readonly content: string;
  readonly caption: string;
}[] {
  return [
    {
      filename: `${user.username}.json`,
      media_type: 'application/json',
      content: JSON.stringify({ outbounds: [{ token: user.subToken }] }),
      caption: `${user.username} — JSON`,
    },
    {
      filename: `${user.username}.txt`,
      media_type: 'text/plain; charset=utf-8',
      content: `vless://${user.subToken}@node.example.test:443`,
      caption: `${user.username} — links`,
    },
  ];
}

/** What the owner's panel generated from a `{"vless": {}}` seed: more than was asked for. */
const GENERATED_PROTOCOLS = ['vless', 'vmess', 'trojan', 'shadowsocks'] as const;

export async function startFakeRickpanel(
  options: FakeRickpanelOptions = {},
): Promise<FakeRickpanel> {
  const username = options.username ?? 'rick-admin';
  const password = options.password ?? 'rick-password';
  const missingSeedStatus = options.missingSeedStatus ?? 422;
  const users = new Map<string, FakeRickpanelUser>();
  const requests: FakeRickpanelRequest[] = [];
  const tokens = new Set<string>();
  let tokenCounter = 0;
  let userCounter = 0;
  let behaviour: RickpanelBehaviour = options.behaviour ?? 'healthy';
  let unprocessableCreates = 0;
  let revokeMode: RickpanelRevokeMode = 'rotates';
  let afterRotation: (() => Promise<void>) | null = null;
  let lostPutAnswers = 0;
  let rateLimitedReads = 0;
  let hiddenReads = 0;
  let droppedReads = 0;
  let unappliedPutFailures = 0;
  let stringNumbers = false;
  let filesBody: string | null = null;
  let subscriptionMode: 'serves' | 'empty' | 'missing' | 'html' = 'serves';
  let omitSubscriptionLink = false;
  let subscriptionContentType = 'text/plain; charset=utf-8';
  const userReadExtras: Record<string, unknown> = {};
  const subUpdatedAt = new Map<string, string>();
  let filesWindowMs = 60_000;
  const filesReadAt = new Map<string, number>();
  let filesCallsForgotten = 0;
  let omitUsedTraffic = false;
  let rotationCounter = 0;
  let listMode: RickpanelListMode = 'documented';
  let listPageCap = 10;
  let beforeListPage: ((offset: number) => void) | null = null;

  const num = (value: number): number | string => (stringNumbers ? String(value) : value);
  const present = (user: FakeRickpanelUser): Record<string, unknown> => ({
    username: user.username,
    status: user.status,
    expire: num(user.expire),
    data_limit: num(user.dataLimit),
    data_limit_reset_strategy: 'no_reset',
    ...(omitUsedTraffic ? {} : { used_traffic: num(user.usedTraffic) }),
    proxies: user.proxies,
    // The document's own `/sub/{username}/{token}` route, as a PATH: a panel does not
    // know which hostname it is reached by.
    ...(omitSubscriptionLink
      ? {}
      : { subscription_url: `/sub/${user.username}/${user.subToken}`, sub_token: user.subToken }),
    ...(subUpdatedAt.has(user.username) ? { sub_updated_at: subUpdatedAt.get(user.username) } : {}),
  });

  const server: Server = createServer((request: IncomingMessage, response: ServerResponse) => {
    const chunks: Buffer[] = [];
    request.on('data', (chunk: Buffer) => chunks.push(chunk));
    request.on('end', () => {
      const body = Buffer.concat(chunks).toString('utf8');
      const rawUrl = request.url ?? '/';
      const method = request.method ?? 'GET';
      requests.push({ method, path: rawUrl, body });

      const json = (status: number, value: unknown): void => {
        response.writeHead(status, { 'content-type': 'application/json' });
        response.end(JSON.stringify(value));
      };
      const path = rawUrl.split('?')[0] ?? '/';

      if (path === '/api/admin/token') {
        const form = new URLSearchParams(body);
        if (form.get('username') !== username || form.get('password') !== password) {
          return void json(401, { detail: 'Incorrect username or password' });
        }
        tokenCounter += 1;
        const minted = `fake-rick-token-${String(tokenCounter)}`;
        tokens.add(minted);
        return void json(200, { access_token: minted, token_type: 'bearer' });
      }

      // C3: the public subscription route — no bearer, the token in the path is the key.
      const sub = /^\/sub\/([^/]+)\/([^/]+)$/.exec(path);
      if (sub !== null && method === 'GET') {
        const held = users.get(decodeURIComponent(sub[1] ?? ''));
        if (subscriptionMode === 'missing' || held === undefined || held.subToken !== sub[2]) {
          return void json(404, { detail: 'Not Found' });
        }
        subUpdatedAt.set(held.username, new Date().toISOString());
        response.writeHead(200, { 'content-type': subscriptionContentType });
        return void response.end(
          subscriptionMode === 'empty'
            ? ''
            : subscriptionMode === 'html'
              ? '<!doctype html><html><body><form action="/login">Sign in</form></body></html>'
              : Buffer.from(fakeRickpanelFiles(held)[1]?.content ?? '', 'utf8').toString('base64'),
        );
      }

      const authorization = String(request.headers['authorization'] ?? '');
      const presented = authorization.startsWith('Bearer ') ? authorization.slice(7) : '';
      if (!tokens.has(presented)) {
        return void json(401, { detail: 'Could not validate credentials' });
      }

      if (path === '/api/system') return void json(200, { version: '2.1.0' });

      if (path === '/api/users' && method === 'GET') {
        const query = new URLSearchParams(rawUrl.split('?')[1] ?? '');
        const offset = Number(query.get('offset') ?? '0');
        const limit = Number(query.get('limit') ?? '0');
        beforeListPage?.(offset);
        const all = [...users.values()];
        const from = listMode === 'ignores-offset' ? 0 : offset;
        const count =
          listMode === 'ignores-limit'
            ? all.length
            : listMode === 'caps-page-size'
              ? Math.min(limit, listPageCap)
              : limit;
        const page = all.slice(from, from + count).map(present);
        if (listMode === 'bare-array') return void json(200, page);
        if (listMode === 'no-total') return void json(200, { users: page });
        return void json(200, { users: page, total: all.length });
      }

      if (path === '/api/user' && method === 'POST') {
        const payload = parse(body);
        // A body validator runs before the handler that applies any rule, so an
        // unseeded create never reaches the user limit.
        if (payload === null || !isSeeded(payload['proxies'])) {
          return void json(missingSeedStatus, {
            detail: [{ loc: ['body', 'proxies'], msg: 'field required', type: 'value_error' }],
          });
        }
        if (unprocessableCreates > 0) {
          unprocessableCreates -= 1;
          return void json(422, { detail: 'unprocessable' });
        }
        if (behaviour === 'refuses-rule') {
          return void json(400, { detail: 'user limit reached for this admin' });
        }
        if (behaviour === 'unprocessable') return void json(422, { detail: 'unprocessable' });
        if (behaviour === 'server-error') return void json(500, { detail: 'boom' });

        const name = String(payload['username'] ?? '');
        if (users.has(name)) return void json(409, { detail: 'username already exists' });
        userCounter += 1;
        const proxies: Record<string, Record<string, string>> = {};
        for (const protocol of GENERATED_PROTOCOLS) {
          proxies[protocol] = { id: `internal-${protocol}-${String(userCounter)}` };
        }
        users.set(name, {
          username: name,
          status: 'active',
          expire: Number(payload['expire'] ?? 0),
          dataLimit: Number(payload['data_limit'] ?? 0),
          usedTraffic: 0,
          proxies,
          subToken: `subtoken${String(userCounter).padStart(8, '0')}`,
        });
        // "The response returns before the nodes have the user": no proof in the body.
        return void json(200, { username: name });
      }

      const revoke = /^\/api\/user\/([^/]+)\/revoke_sub$/.exec(path);
      if (revoke !== null && method === 'POST') {
        const held = users.get(decodeURIComponent(revoke[1] ?? ''));
        if (held === undefined) return void json(404, { detail: 'User not found' });
        if (revokeMode === 'fails-500') return void json(500, { detail: 'boom' });
        if (revokeMode === 'no-op-200') return void json(200, present(held));
        rotationCounter += 1;
        held.subToken = `rotated${String(rotationCounter).padStart(8, '0')}`;
        if (revokeMode === 'rotates-then-500') return void json(500, { detail: 'boom' });
        if (revokeMode === 'rotates-then-drops') return void response.destroy();
        // The body is not evidence and the adapter does not read it: the link comes
        // from the read-back, as it does after a create.
        const hook = afterRotation;
        if (hook === null) return void json(200, present(held));
        // The rotation is done and its answer has not left: what a caller does here
        // happens while the call is on the wire, from the caller's side.
        void hook().then(() => json(200, present(held)));
        return;
      }

      const files = /^\/api\/user\/([^/]+)\/files$/.exec(path);
      if (files !== null && method === 'GET') {
        const held = users.get(decodeURIComponent(files[1] ?? ''));
        // "A user you do not own answers 404, the same as one that does not exist."
        if (held === undefined) return void json(404, { detail: 'User not found' });
        const last = filesReadAt.get(held.username);
        const now = Date.now();
        if (filesWindowMs > 0 && last !== undefined && now - last < filesWindowMs) {
          response.writeHead(429, {
            'content-type': 'application/json',
            'retry-after': String(Math.ceil((filesWindowMs - (now - last)) / 1000)),
          });
          return void response.end(JSON.stringify({ detail: 'Too many requests' }));
        }
        filesReadAt.set(held.username, now);
        if (filesBody !== null) {
          response.writeHead(200, { 'content-type': 'application/json' });
          return void response.end(filesBody);
        }
        return void json(
          200,
          fakeRickpanelFiles(held).map((one) => ({
            filename: one.filename,
            media_type: one.media_type,
            caption: one.caption,
            content_b64: Buffer.from(one.content, 'utf8').toString('base64'),
          })),
        );
      }

      const single = /^\/api\/user\/([^/]+)$/.exec(path);
      if (single !== null) {
        const name = decodeURIComponent(single[1] ?? '');
        const held = users.get(name);
        if (method === 'GET') {
          if (rateLimitedReads > 0) {
            rateLimitedReads -= 1;
            return void json(429, { detail: 'slow down' });
          }
          if (droppedReads > 0) {
            droppedReads -= 1;
            return void response.destroy();
          }
          if (hiddenReads > 0) {
            hiddenReads -= 1;
            return void json(404, { detail: 'User not found' });
          }
          if (held === undefined) return void json(404, { detail: 'User not found' });
          return void json(200, { ...present(held), ...userReadExtras });
        }
        if (method === 'PUT') {
          if (held === undefined) return void json(404, { detail: 'User not found' });
          if (unappliedPutFailures > 0) {
            unappliedPutFailures -= 1;
            return void json(500, { detail: 'boom' });
          }
          const payload = parse(body) ?? {};
          if (typeof payload['status'] === 'string') held.status = payload['status'];
          if (typeof payload['expire'] === 'number') held.expire = payload['expire'];
          if (typeof payload['data_limit'] === 'number') held.dataLimit = payload['data_limit'];
          if (lostPutAnswers > 0) {
            // Applied, and the answer lost: what a replay of an idempotent write is for.
            lostPutAnswers -= 1;
            return void json(500, { detail: 'boom' });
          }
          return void json(200, present(held));
        }
        if (method === 'DELETE') {
          if (held === undefined) return void json(404, { detail: 'User not found' });
          users.delete(name);
          return void json(200, { detail: 'User successfully deleted' });
        }
      }
      json(404, { detail: 'Not Found' });
    });
  });

  server.listen(0, options.host ?? '127.0.0.1');
  await once(server, 'listening');
  const address = server.address() as AddressInfo;
  const host = options.host ?? '127.0.0.1';

  return {
    baseUrl: `http://${host}:${String(address.port)}`,
    username,
    password,
    get behaviour() {
      return behaviour;
    },
    set behaviour(next: RickpanelBehaviour) {
      behaviour = next;
    },
    get unprocessableCreates() {
      return unprocessableCreates;
    },
    set unprocessableCreates(next: number) {
      unprocessableCreates = next;
    },
    get rateLimitedReads() {
      return rateLimitedReads;
    },
    set rateLimitedReads(next: number) {
      rateLimitedReads = next;
    },
    get hiddenReads() {
      return hiddenReads;
    },
    set hiddenReads(next: number) {
      hiddenReads = next;
    },
    get droppedReads() {
      return droppedReads;
    },
    set droppedReads(next: number) {
      droppedReads = next;
    },
    get unappliedPutFailures() {
      return unappliedPutFailures;
    },
    set unappliedPutFailures(next: number) {
      unappliedPutFailures = next;
    },
    get stringNumbers() {
      return stringNumbers;
    },
    set stringNumbers(next: boolean) {
      stringNumbers = next;
    },
    get omitUsedTraffic() {
      return omitUsedTraffic;
    },
    set omitUsedTraffic(next: boolean) {
      omitUsedTraffic = next;
    },
    get lostPutAnswers() {
      return lostPutAnswers;
    },
    set lostPutAnswers(next: number) {
      lostPutAnswers = next;
    },
    putCalls: () => requests.filter((one) => one.method === 'PUT').length,
    get afterRotation() {
      return afterRotation;
    },
    set afterRotation(next: (() => Promise<void>) | null) {
      afterRotation = next;
    },
    get revokeMode() {
      return revokeMode;
    },
    set revokeMode(next: RickpanelRevokeMode) {
      revokeMode = next;
    },
    get filesBody() {
      return filesBody;
    },
    set filesBody(next: string | null) {
      filesBody = next;
    },
    get filesWindowMs() {
      return filesWindowMs;
    },
    set filesWindowMs(next: number) {
      filesWindowMs = next;
    },
    filesCalls: () =>
      requests.filter((one) => one.method === 'GET' && /\/files(\?|$)/.test(one.path)).length -
      filesCallsForgotten,
    forgetFileReads: () => {
      filesReadAt.clear();
      filesCallsForgotten = requests.filter(
        (one) => one.method === 'GET' && /\/files(\?|$)/.test(one.path),
      ).length;
    },
    requests,
    users,
    get subscriptionMode() {
      return subscriptionMode;
    },
    set subscriptionMode(next: 'serves' | 'empty' | 'missing' | 'html') {
      subscriptionMode = next;
    },
    get subscriptionContentType() {
      return subscriptionContentType;
    },
    set subscriptionContentType(next: string) {
      subscriptionContentType = next;
    },
    userReadExtras,
    get omitSubscriptionLink() {
      return omitSubscriptionLink;
    },
    set omitSubscriptionLink(next: boolean) {
      omitSubscriptionLink = next;
    },
    subscriptionReads: () =>
      requests.filter((one) => one.method === 'GET' && one.path.startsWith('/sub/')).length,
    get listMode() {
      return listMode;
    },
    set listMode(next: RickpanelListMode) {
      listMode = next;
    },
    get listPageCap() {
      return listPageCap;
    },
    set listPageCap(next: number) {
      listPageCap = next;
    },
    get beforeListPage() {
      return beforeListPage;
    },
    set beforeListPage(next: ((offset: number) => void) | null) {
      beforeListPage = next;
    },
    listCalls: () =>
      requests.filter((one) => one.method === 'GET' && one.path.split('?')[0] === '/api/users')
        .length,
    seedUser: (name: string, fields: Partial<Omit<FakeRickpanelUser, 'username'>> = {}) => {
      userCounter += 1;
      users.set(name, {
        username: name,
        status: fields.status ?? 'active',
        expire: fields.expire ?? 0,
        dataLimit: fields.dataLimit ?? 0,
        usedTraffic: fields.usedTraffic ?? 0,
        proxies: fields.proxies ?? { vless: { id: `seeded-${String(userCounter)}` } },
        subToken: fields.subToken ?? `seeded-token-${String(userCounter)}`,
      });
    },
    createCalls: () =>
      requests.filter((one) => one.method === 'POST' && one.path.split('?')[0] === '/api/user')
        .length,
    revokeCalls: () =>
      requests.filter((one) => one.method === 'POST' && one.path.endsWith('/revoke_sub')).length,
    close: async () => {
      server.closeAllConnections();
      await new Promise<void>((resolve) => server.close(() => resolve()));
    },
  };
}

function parse(body: string): Record<string, unknown> | null {
  try {
    const value: unknown = JSON.parse(body);
    return typeof value === 'object' && value !== null && !Array.isArray(value)
      ? (value as Record<string, unknown>)
      : null;
  } catch {
    return null;
  }
}

/** A non-empty object: the one shape a real panel was seen to accept. */
function isSeeded(value: unknown): boolean {
  return (
    typeof value === 'object' &&
    value !== null &&
    !Array.isArray(value) &&
    Object.keys(value).length > 0
  );
}
