import { createServer, type IncomingMessage, type Server, type ServerResponse } from 'node:http';
import { once } from 'node:events';
import type { AddressInfo } from 'node:net';

/**
 * A deterministic RickPanel, on a real socket.
 *
 * Built from two sources, and it says which is which:
 *
 *   - `rickpanel-openapi.json`, the per-admin document the owner attached. Its
 *     descriptions are the contract (`docs/rickpanel-adapter-audit.md` §1): a
 *     form-encoded token exchange, a 400 "saying which rule was hit", a 409 for a
 *     name in use, and a create that "returns before the nodes have the user".
 *   - the owner's direct calls to a correctly connected panel
 *     (`docs/rickpanel-create-hotfix.md` §2). They are where this fake refuses a
 *     create with no `proxies`, where an accepted create comes back holding a
 *     credential for SEVERAL protocols, an active status, a `subscription_url` and a
 *     `sub_token`, and where `revoke_sub` answers 200 and changes the token and
 *     nothing else.
 *
 * One thing in here is NOT evidence and is marked as such: the status a real panel
 * answers an unseeded create with has not been captured (`OQ-RP-06`). It is a
 * setting, so a test can name the status it depends on.
 *
 * Real sockets and the real `SafeHttpClient` against them, for the reason the other
 * two fakes use them: mocking the client away erases URL composition and whether a
 * credential can escape to another origin.
 */

export type RickpanelBehaviour =
  /** Answers as the owner's panel did. */
  | 'healthy'
  /** Every create answers 400 — a rule was hit: a user limit, a service rule. */
  | 'refuses-rule'
  /** Every create answers 422. What a real panel means by one is `OQ-RP-06`. */
  | 'unprocessable'
  /** Every create answers 500 without creating anything. */
  | 'server-error';

/**
 * What `POST /api/user/{username}/revoke_sub` does.
 *
 * `rotates` is the owner's measurement (`docs/rickpanel-rotate-audit.md` §2): a 200, and
 * afterwards a new token and a new link with nothing else changed. The others are the
 * shapes the adapter's read-back exists for, and none is evidence about a real panel.
 */
export type RickpanelRevokeMode =
  | 'rotates'
  /** The rotation takes effect and the answer is lost: a 500 after the write. */
  | 'rotates-then-500'
  /** The rotation takes effect and the connection drops without an answer. */
  | 'rotates-then-drops'
  /** A 500 and no rotation. */
  | 'fails-500'
  /** A 200 that changes nothing. */
  | 'no-op-200';

export interface FakeRickpanelOptions {
  readonly username?: string;
  readonly password?: string;
  readonly behaviour?: RickpanelBehaviour;
  readonly host?: string;
  /** The status for a create whose `proxies` is missing or empty. Unmeasured: `OQ-RP-06`. */
  readonly missingSeedStatus?: number;
}

export interface FakeRickpanelUser {
  readonly username: string;
  status: string;
  /** Epoch SECONDS; 0 is the panel's "never". */
  expire: number;
  /** Bytes; 0 is the panel's "unlimited". */
  dataLimit: number;
  usedTraffic: number;
  /** Generated by the panel, per protocol. Never a thing a customer should see. */
  readonly proxies: Readonly<Record<string, Readonly<Record<string, string>>>>;
  /** Replaced by `revoke_sub`. */
  subToken: string;
}

export interface FakeRickpanelRequest {
  readonly method: string;
  readonly path: string;
  readonly body: string;
}

export interface FakeRickpanel {
  readonly baseUrl: string;
  readonly username: string;
  readonly password: string;
  behaviour: RickpanelBehaviour;
  /**
   * How many of the NEXT creates answer 422 before the panel behaves as `behaviour`
   * says. A panel that recovers between two attempts, which is the case a reconcile
   * exists for.
   */
  unprocessableCreates: number;
  /** What the next `revoke_sub` does. */
  revokeMode: RickpanelRevokeMode;
  /**
   * Run after a `rotates` revoke has changed the token and before it answers: a hook
   * for a test to change the world while the rotation is on the wire.
   */
  afterRotation: (() => Promise<void>) | null;
  readonly requests: readonly FakeRickpanelRequest[];
  /** Everything this panel holds, keyed by username — the observer's view. */
  readonly users: ReadonlyMap<string, FakeRickpanelUser>;
  /** How many creates reached the panel, accepted or not. */
  createCalls(): number;
  /** How many `revoke_sub` calls reached the panel, whatever they did. */
  revokeCalls(): number;
  close(): Promise<void>;
}

/** What the owner's panel generated from a `{"vless": {}}` seed: more than was asked for. */
const GENERATED_PROTOCOLS = ['vless', 'vmess', 'trojan', 'shadowsocks'] as const;

export async function startFakeRickpanel(
  options: FakeRickpanelOptions = {},
): Promise<FakeRickpanel> {
  const username = options.username ?? 'rick-admin';
  const password = options.password ?? 'rick-password';
  const missingSeedStatus = options.missingSeedStatus ?? 422;
  const users = new Map<string, FakeRickpanelUser>();
  const requests: FakeRickpanelRequest[] = [];
  const tokens = new Set<string>();
  let tokenCounter = 0;
  let userCounter = 0;
  let behaviour: RickpanelBehaviour = options.behaviour ?? 'healthy';
  let unprocessableCreates = 0;
  let revokeMode: RickpanelRevokeMode = 'rotates';
  let afterRotation: (() => Promise<void>) | null = null;
  let rotationCounter = 0;

  const present = (user: FakeRickpanelUser): Record<string, unknown> => ({
    username: user.username,
    status: user.status,
    expire: user.expire,
    data_limit: user.dataLimit,
    data_limit_reset_strategy: 'no_reset',
    used_traffic: user.usedTraffic,
    proxies: user.proxies,
    // The document's own `/sub/{username}/{token}` route, as a PATH: a panel does not
    // know which hostname it is reached by.
    subscription_url: `/sub/${user.username}/${user.subToken}`,
    sub_token: user.subToken,
  });

  const server: Server = createServer((request: IncomingMessage, response: ServerResponse) => {
    const chunks: Buffer[] = [];
    request.on('data', (chunk: Buffer) => chunks.push(chunk));
    request.on('end', () => {
      const body = Buffer.concat(chunks).toString('utf8');
      const rawUrl = request.url ?? '/';
      const method = request.method ?? 'GET';
      requests.push({ method, path: rawUrl, body });

      const json = (status: number, value: unknown): void => {
        response.writeHead(status, { 'content-type': 'application/json' });
        response.end(JSON.stringify(value));
      };
      const path = rawUrl.split('?')[0] ?? '/';

      if (path === '/api/admin/token') {
        const form = new URLSearchParams(body);
        if (form.get('username') !== username || form.get('password') !== password) {
          return void json(401, { detail: 'Incorrect username or password' });
        }
        tokenCounter += 1;
        const minted = `fake-rick-token-${String(tokenCounter)}`;
        tokens.add(minted);
        return void json(200, { access_token: minted, token_type: 'bearer' });
      }

      const authorization = String(request.headers['authorization'] ?? '');
      const presented = authorization.startsWith('Bearer ') ? authorization.slice(7) : '';
      if (!tokens.has(presented)) {
        return void json(401, { detail: 'Could not validate credentials' });
      }

      if (path === '/api/system') return void json(200, { version: '2.1.0' });

      if (path === '/api/user' && method === 'POST') {
        const payload = parse(body);
        // A body validator runs before the handler that applies any rule, so an
        // unseeded create never reaches the user limit.
        if (payload === null || !isSeeded(payload['proxies'])) {
          return void json(missingSeedStatus, {
            detail: [{ loc: ['body', 'proxies'], msg: 'field required', type: 'value_error' }],
          });
        }
        if (unprocessableCreates > 0) {
          unprocessableCreates -= 1;
          return void json(422, { detail: 'unprocessable' });
        }
        if (behaviour === 'refuses-rule') {
          return void json(400, { detail: 'user limit reached for this admin' });
        }
        if (behaviour === 'unprocessable') return void json(422, { detail: 'unprocessable' });
        if (behaviour === 'server-error') return void json(500, { detail: 'boom' });

        const name = String(payload['username'] ?? '');
        if (users.has(name)) return void json(409, { detail: 'username already exists' });
        userCounter += 1;
        const proxies: Record<string, Record<string, string>> = {};
        for (const protocol of GENERATED_PROTOCOLS) {
          proxies[protocol] = { id: `internal-${protocol}-${String(userCounter)}` };
        }
        users.set(name, {
          username: name,
          status: 'active',
          expire: Number(payload['expire'] ?? 0),
          dataLimit: Number(payload['data_limit'] ?? 0),
          usedTraffic: 0,
          proxies,
          subToken: `subtoken${String(userCounter).padStart(8, '0')}`,
        });
        // "The response returns before the nodes have the user": no proof in the body.
        return void json(200, { username: name });
      }

      const revoke = /^\/api\/user\/([^/]+)\/revoke_sub$/.exec(path);
      if (revoke !== null && method === 'POST') {
        const held = users.get(decodeURIComponent(revoke[1] ?? ''));
        if (held === undefined) return void json(404, { detail: 'User not found' });
        if (revokeMode === 'fails-500') return void json(500, { detail: 'boom' });
        if (revokeMode === 'no-op-200') return void json(200, present(held));
        rotationCounter += 1;
        held.subToken = `rotated${String(rotationCounter).padStart(8, '0')}`;
        if (revokeMode === 'rotates-then-500') return void json(500, { detail: 'boom' });
        if (revokeMode === 'rotates-then-drops') return void response.destroy();
        // The body is not evidence and the adapter does not read it: the link comes
        // from the read-back, as it does after a create.
        const hook = afterRotation;
        if (hook === null) return void json(200, present(held));
        // The rotation is done and its answer has not left: what a caller does here
        // happens while the call is on the wire, from the caller's side.
        void hook().then(() => json(200, present(held)));
        return;
      }

      const single = /^\/api\/user\/([^/]+)$/.exec(path);
      if (single !== null) {
        const name = decodeURIComponent(single[1] ?? '');
        const held = users.get(name);
        if (method === 'GET') {
          if (held === undefined) return void json(404, { detail: 'User not found' });
          return void json(200, present(held));
        }
        if (method === 'PUT') {
          if (held === undefined) return void json(404, { detail: 'User not found' });
          const payload = parse(body) ?? {};
          if (typeof payload['status'] === 'string') held.status = payload['status'];
          if (typeof payload['expire'] === 'number') held.expire = payload['expire'];
          if (typeof payload['data_limit'] === 'number') held.dataLimit = payload['data_limit'];
          return void json(200, present(held));
        }
        if (method === 'DELETE') {
          if (held === undefined) return void json(404, { detail: 'User not found' });
          users.delete(name);
          return void json(200, { detail: 'User successfully deleted' });
        }
      }
      json(404, { detail: 'Not Found' });
    });
  });

  server.listen(0, options.host ?? '127.0.0.1');
  await once(server, 'listening');
  const address = server.address() as AddressInfo;
  const host = options.host ?? '127.0.0.1';

  return {
    baseUrl: `http://${host}:${String(address.port)}`,
    username,
    password,
    get behaviour() {
      return behaviour;
    },
    set behaviour(next: RickpanelBehaviour) {
      behaviour = next;
    },
    get unprocessableCreates() {
      return unprocessableCreates;
    },
    set unprocessableCreates(next: number) {
      unprocessableCreates = next;
    },
    get afterRotation() {
      return afterRotation;
    },
    set afterRotation(next: (() => Promise<void>) | null) {
      afterRotation = next;
    },
    get revokeMode() {
      return revokeMode;
    },
    set revokeMode(next: RickpanelRevokeMode) {
      revokeMode = next;
    },
    requests,
    users,
    createCalls: () =>
      requests.filter((one) => one.method === 'POST' && one.path.split('?')[0] === '/api/user')
        .length,
    revokeCalls: () =>
      requests.filter((one) => one.method === 'POST' && one.path.endsWith('/revoke_sub')).length,
    close: async () => {
      server.closeAllConnections();
      await new Promise<void>((resolve) => server.close(() => resolve()));
    },
  };
}

function parse(body: string): Record<string, unknown> | null {
  try {
    const value: unknown = JSON.parse(body);
    return typeof value === 'object' && value !== null && !Array.isArray(value)
      ? (value as Record<string, unknown>)
      : null;
  } catch {
    return null;
  }
}

/** A non-empty object: the one shape a real panel was seen to accept. */
function isSeeded(value: unknown): boolean {
  return (
    typeof value === 'object' &&
    value !== null &&
    !Array.isArray(value) &&
    Object.keys(value).length > 0
  );
}
