#!/usr/bin/env bash
#
# Migration drift check.
#
# Regenerates migrations from the schema and fails if that produces anything
# new. A schema change that never became a migration is a deployment that works
# on the developer's machine and nowhere else.
#
# Migrations are forward-only: an applied migration is never edited, and a
# destructive change is expressed as expand/contract across two releases.

set -euo pipefail
cd "$(dirname "$0")/../apps/api"

# Hash the file CONTENTS, not just the names, so a regenerated file is caught as
# well as a new one.
BEFORE=$(find drizzle -name '*.sql' | sort | xargs md5sum | md5sum)

# drizzle-kit writes three things: the .sql, a meta snapshot, and a journal
# entry. An earlier version of this check deleted only the .sql, so every run
# that found drift left a scratch entry named `drift-check` in the journal and
# an orphan snapshot behind — repository state altered by a read-only check.
# Save what we are about to disturb, and restore it whatever happens.
JOURNAL=drizzle/meta/_journal.json
SNAPSHOTS_BEFORE=$(find drizzle/meta -name '*_snapshot.json' | sort)
cp "$JOURNAL" "$JOURNAL.drift-backup"

cleanup() {
  find drizzle -name '*drift-check*' -delete
  # Any snapshot that did not exist before this run is ours to remove.
  for snapshot in $(find drizzle/meta -name '*_snapshot.json' | sort); do
    # `grep -c`, which reads its whole input, not `grep -qxF`, which exits on
    # the first match and can leave `echo` dying of SIGPIPE — returning 141
    # under `pipefail` exactly when the snapshot IS known. This branch DELETES,
    # so the wrong answer here removes a checked-in snapshot.
    known="$(echo "$SNAPSHOTS_BEFORE" | grep -cxF "$snapshot" || true)"
    [ "${known:-0}" -gt 0 ] || rm -f "$snapshot"
  done
  mv -f "$JOURNAL.drift-backup" "$JOURNAL"
}
trap cleanup EXIT

DATABASE_URL="${DATABASE_URL:-postgres://nexa:nexa@127.0.0.1:5432/nexa_dev}" \
  pnpm exec drizzle-kit generate --name drift-check >/dev/null 2>&1 || true

AFTER=$(find drizzle -name '*.sql' | sort | xargs md5sum | md5sum)

if [ "$BEFORE" != "$AFTER" ]; then
  echo "FAIL  The Drizzle schema and the migration files disagree."
  echo "      A new migration was generated by this check:"
  find drizzle -name '*drift-check*' -print
  echo "      Run 'pnpm db:generate' with a meaningful name, review the SQL, and commit it."
  exit 1
fi

echo "ok    schema and migrations agree"
