#!/usr/bin/env bash
#
# Migration drift check.
#
# Regenerates migrations from the schema and fails if that produces anything
# new. A schema change that never became a migration is a deployment that works
# on the developer's machine and nowhere else.
#
# Migrations are forward-only: an applied migration is never edited, and a
# destructive change is expressed as expand/contract across two releases.

set -euo pipefail
cd "$(dirname "$0")/../apps/api"

# Hash the file CONTENTS, not just the names, so a regenerated file is caught as
# well as a new one.
BEFORE=$(find drizzle -name '*.sql' | sort | xargs md5sum | md5sum)

# drizzle-kit writes three things: the .sql, a meta snapshot, and a journal
# entry. An earlier version of this check deleted only the .sql, so every run
# that found drift left a scratch entry named `drift-check` in the journal and
# an orphan snapshot behind — repository state altered by a read-only check.
# Save what we are about to disturb, and restore it whatever happens.
JOURNAL=drizzle/meta/_journal.json
SNAPSHOTS_BEFORE=$(find drizzle/meta -name '*_snapshot.json' | sort)
cp "$JOURNAL" "$JOURNAL.drift-backup"

cleanup() {
  find drizzle -name '*drift-check*' -delete
  # Any snapshot that did not exist before this run is ours to remove.
  for snapshot in $(find drizzle/meta -name '*_snapshot.json' | sort); do
    # `grep -c`, which reads its whole input, not `grep -qxF`, which exits on
    # the first match and can leave `echo` dying of SIGPIPE — returning 141
    # under `pipefail` exactly when the snapshot IS known. This branch DELETES,
    # so the wrong answer here removes a checked-in snapshot.
    known=0
    status=0
    known="$(echo "$SNAPSHOTS_BEFORE" | grep -cxF "$snapshot")" || status=$?
    # Exit 1 means "not found", which is the delete case. Anything above that
    # is an error, and this branch DELETES — so a read failure must not read as
    # "unknown, remove it".
    #
    # `break`, not `exit`: this runs inside the EXIT trap, and exiting from here
    # skips the journal restore below — leaving the repository with a
    # drizzle-modified _journal.json and an orphan backup, which is the exact
    # state this function exists to prevent. Stop deleting, finish cleaning up,
    # and report at the end.
    if [ "$status" -gt 1 ]; then
      echo "cannot read the snapshot list (grep exited $status); stopped removing snapshots" >&2
      CLEANUP_FAILED=1
      break
    fi
    [ "${known:-0}" -gt 0 ] || rm -f "$snapshot"
  done
  # The journal is restored unconditionally, even after the failure above.
  # This check must not be able to leave the repository altered.
  mv -f "$JOURNAL.drift-backup" "$JOURNAL"
  [ "${CLEANUP_FAILED:-0}" -eq 0 ] || {
    echo "the drift check could not clean up fully; inspect drizzle/meta before committing" >&2
    return 1
  }
  return 0
}
CLEANUP_FAILED=0
trap cleanup EXIT

# The generator's exit code decides whether this check ran at all.
#
# It used to be `|| true` with the output discarded, which made the check pass
# whenever the tool FAILED: no `.sql` is written, so the before and after
# checksums match, and it printed `ok schema and migrations agree`. A missing
# config, an unparseable schema, an interactive rename prompt on a non-TTY or a
# devDependency that did not install would all have reported agreement on a
# schema nobody compared. This is the only drift gate in CI, and
# `check-shell.sh` states the rule it was breaking: a check that silently
# passes when its tool is missing is worse than no check at all.
GENERATE_LOG="$(mktemp)"
GENERATE_STATUS=0
DATABASE_URL="${DATABASE_URL:-postgres://nexa:nexa@127.0.0.1:5432/nexa_dev}" \
  pnpm exec drizzle-kit generate --name drift-check >"$GENERATE_LOG" 2>&1 || GENERATE_STATUS=$?

if [ "$GENERATE_STATUS" -ne 0 ]; then
  echo "FAIL  drizzle-kit generate could not run, so nothing was compared."
  echo "      This check cannot report agreement it did not establish."
  sed 's/^/      /' "$GENERATE_LOG" >&2
  rm -f "$GENERATE_LOG"
  exit 1
fi
rm -f "$GENERATE_LOG"

AFTER=$(find drizzle -name '*.sql' | sort | xargs md5sum | md5sum)

if [ "$BEFORE" != "$AFTER" ]; then
  echo "FAIL  The Drizzle schema and the migration files disagree."
  echo "      A new migration was generated by this check:"
  find drizzle -name '*drift-check*' -print
  echo "      Run 'pnpm db:generate' with a meaningful name, review the SQL, and commit it."
  exit 1
fi

echo "ok    schema and migrations agree"
