#!/usr/bin/env bash
#
# Migration drift check.
#
# Regenerates migrations from the schema and fails if that produces anything
# new. A schema change that never became a migration is a deployment that works
# on the developer's machine and nowhere else.
#
# Migrations are forward-only: an applied migration is never edited, and a
# destructive change is expressed as expand/contract across two releases.

set -euo pipefail
cd "$(dirname "$0")/../apps/api"

# Hash the file CONTENTS, not just the names, so a regenerated file is caught as
# well as a new one.
BEFORE=$(find drizzle -name '*.sql' | sort | xargs md5sum | md5sum)

DATABASE_URL="${DATABASE_URL:-postgres://nexa:nexa@127.0.0.1:5432/nexa_dev}" \
  pnpm exec drizzle-kit generate --name drift-check >/dev/null 2>&1 || true

AFTER=$(find drizzle -name '*.sql' | sort | xargs md5sum | md5sum)

if [ "$BEFORE" != "$AFTER" ]; then
  echo "FAIL  The Drizzle schema and the migration files disagree."
  echo "      A new migration was generated by this check:"
  find drizzle -name '*drift-check*' -print
  echo "      Run 'pnpm db:generate' with a meaningful name, review the SQL, and commit it."
  find drizzle -name '*drift-check*' -delete
  exit 1
fi

echo "ok    schema and migrations agree"
