import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import {
  PAYMENT_GATEWAY_TOPUP_CASHBACK_PERCENT_MAX,
  PAYMENT_GATEWAY_TOPUP_CASHBACK_PERCENT_MIN,
  type PaymentGatewayView,
  type SalesCurrencyCode,
} from '@nexa/contracts';
import {
  fetchPaymentGateways,
  setPaymentGatewayCredential,
  setPaymentGatewayStatus,
  updatePaymentGateway,
} from '../api/client';
import { formatMoneyText, formatTimestamp } from '../format';
import { useSubmissionKey } from '../submission-key';
import { queryState } from '../view-state';
import { t } from '../i18n/web.fa';
import { messageFor } from './settings';
import {
  Badge,
  Banner,
  Card,
  DataTable,
  Empty,
  Field,
  Ltr,
  PageHead,
  StateSwitch,
  Switch,
  useToast,
  type Column,
} from '../ui/kit';

/**
 * Payment routes — which ways a customer may pay, and under what conditions.
 *
 * Not the same screen as Payment accounts, and the distinction is the whole point: an
 * account is WHERE the money goes, a route is WHETHER this way of paying is offered to
 * this customer at all. The legacy system keeps both under `💎 مالی` and this product
 * keeps them apart, because `payments.accounts.edit` and `payments.gateways.edit` are
 * different authorities with different blast radii.
 *
 * **No Add, and no Delete.** A route is `(tenant, provider)` where the provider comes
 * from a closed catalogue of what this release can actually operate, so the roster is
 * fixed by construction — the shape `WEB-BR-012` reads off the legacy panel, a fixed
 * eleven with no Add Gateway. `web.payment_gateways_hint` says so on the screen, because
 * a missing button an operator cannot explain is a defect report.
 *
 * **Two writes, two buttons, two audit rows.** Change the configuration, or switch the
 * route on and off. Separate because switching off a payment route is the one change a
 * customer notices immediately, and folding it into the form would make "who stopped
 * accepting card-to-card, and when" answerable only by diffing two payloads.
 *
 * **A credential is write-only.** A route that needs one (TonPays, WP11A) shows whether
 * its API key is configured and when it was last replaced — never the key, and never a
 * masked copy in a field that could be resubmitted. Replacing it is its own form with an
 * empty input, and enabling the route is refused by the server until one is stored. The
 * callback URL is generated by the server and shown for diagnostics, never edited.
 *
 * **`0` means "no condition", everywhere.** It is the legacy form's own semantics
 * (`WEB-BR-014`) and it is kept consistent across the amount bounds and the three
 * eligibility counters so an operator holds one convention rather than two.
 */

const EMPTY_FORM = {
  displayName: '',
  instructions: '',
  minAmountMinor: '0',
  maxAmountMinor: '0',
  activateAfterPayments: '0',
  deactivateAfterPayments: '0',
  activateAfterAccountDays: '0',
  sortOrder: '0',
  topupCashbackPercent: '0',
  /*
   * The two purpose switches (customer UX completion §D/§F). ON by default, which is
   * the state every route starts in; the form shows both so an operator who switches
   * one off can see the other is still on.
   */
  allowServicePurchase: true,
  allowWalletTopup: true,
};

type FormState = typeof EMPTY_FORM;

function formOf(gateway: PaymentGatewayView): FormState {
  return {
    displayName: gateway.displayName ?? '',
    instructions: gateway.instructions ?? '',
    minAmountMinor: gateway.minAmountMinor,
    maxAmountMinor: gateway.maxAmountMinor,
    activateAfterPayments: String(gateway.eligibility.activateAfterPayments),
    deactivateAfterPayments: String(gateway.eligibility.deactivateAfterPayments),
    activateAfterAccountDays: String(gateway.eligibility.activateAfterAccountDays),
    sortOrder: String(gateway.sortOrder),
    topupCashbackPercent: String(gateway.topupCashbackPercent),
    allowServicePurchase: gateway.allowServicePurchase,
    allowWalletTopup: gateway.allowWalletTopup,
  };
}

/**
 * The route's name for an operator: what they called it, or the product's own name.
 *
 * A null `displayName` is not blank — it means the installation has not renamed the
 * route — so the table says which of the two it is looking at rather than showing an
 * empty cell an operator would try to fill.
 */
function nameOf(gateway: PaymentGatewayView): string {
  if (gateway.displayName !== null) return gateway.displayName;
  switch (gateway.provider) {
    case 'MANUAL_TRANSFER':
      return t('web.payment_gateway_provider_manual_transfer');
    case 'TONPAYS':
      return t('web.payment_gateway_provider_tonpays');
  }
}

/**
 * A bound, or the words for "no bound". `0` is off, on both sides.
 *
 * `formatMoneyText` rather than `formatMoney`, because this is a table cell and the
 * amount and its unit belong together in one string here. Never abbreviated and never
 * rounded — a limit an operator reads as 5,000,000 and typed as 500,000 is the wrong
 * kind of surprise.
 */
function boundOf(minor: string, currency: SalesCurrencyCode): string {
  return minor === '0'
    ? t('web.payment_gateway_unbounded')
    : formatMoneyText({ amountMinor: minor, currency });
}

/** Digits only, and anything else becomes zero — which is this form's "no condition". */
function counted(value: string): number {
  const parsed = Number(value.trim());
  return Number.isSafeInteger(parsed) && parsed >= 0 ? parsed : 0;
}

/**
 * A minor-unit amount as a decimal STRING, never a number — or `null` when what was
 * typed is not one.
 *
 * The browser must not COMPUTE it: JSON has no bigint and a `number` is the float the
 * money model refuses, silently, above 2^53.
 *
 * It must not SILENTLY CORRECT it either, which is what this used to do. Deleting every
 * non-digit turned `-100` into a positive `100` and `1e6` into `16`, then submitted the
 * result as though the operator had typed it. The server saw a valid number and had
 * nothing to report. These two fields decide which customer payments a route accepts, so
 * a stored bound that differs from the one on screen is the write-only-setting failure
 * this codebase is organised against, with money attached.
 *
 * Grouping separators and Persian or Arabic-Indic digits ARE accepted, because those are
 * ways of writing the same number and an operator typing `۱٬۰۰۰٬۰۰۰` means exactly what
 * the digits say. A sign, a decimal point, an exponent or any other character is not a
 * formatting variant of a whole number of minor units, so it is refused rather than
 * reinterpreted, and the caller reports it against the field.
 *
 * Empty still means "no bound" and travels as `'0'`, unchanged.
 */
const GROUPING = /[\s,\u066C\u2009\u202F']/gu;

/**
 * The top-up gift as the whole percentage the route stores (Payment File 02 §17, D5), or
 * `null` when what was typed is not one: an integer from 0 to 100, in Latin, Persian or
 * Arabic-Indic digits, an optional trailing `%`. Refused rather than clamped or rounded —
 * `minorOf`'s rule: a stored figure that differs from the one on screen is the
 * write-only-setting failure, and this one decides how much money a customer is given.
 */
export function percentOf(value: string): number | null {
  const latin = value
    .trim()
    .replace(/[%\u066A]$/u, '')
    .trim()
    .replace(/[\u06F0-\u06F9]/gu, (d) => String(d.charCodeAt(0) - 0x06f0))
    .replace(/[\u0660-\u0669]/gu, (d) => String(d.charCodeAt(0) - 0x0660));
  if (!/^[0-9]{1,3}$/u.test(latin)) return null;
  const parsed = Number(latin);
  return parsed >= PAYMENT_GATEWAY_TOPUP_CASHBACK_PERCENT_MIN &&
    parsed <= PAYMENT_GATEWAY_TOPUP_CASHBACK_PERCENT_MAX
    ? parsed
    : null;
}

export function minorOf(value: string): string | null {
  const latin = value
    .trim()
    .replace(GROUPING, '')
    .replace(/[\u06F0-\u06F9]/gu, (d) => String(d.charCodeAt(0) - 0x06f0))
    .replace(/[\u0660-\u0669]/gu, (d) => String(d.charCodeAt(0) - 0x0660));
  if (latin === '') return '0';
  if (!/^[0-9]+$/u.test(latin)) return null;
  return latin.replace(/^0+(?=\d)/u, '');
}

/**
 * `mayEdit` is passed, never derived from `denied`.
 *
 * The rule the Codex review of PR #34 established on the accounts screen, applied here
 * from the start: reaching this page takes `payments.gateways.view` and writing takes
 * `payments.gateways.edit`, which the service charges on its own. So the two keys are
 * genuinely different questions, and deriving the page from `denied` would hand the
 * seeded view-only roles (operator, observer) every control and teach them about the
 * refusal by pressing one. Drawing a control nobody may use is `UNK-ADM-001` from the
 * other end.
 */
export function PaymentGatewaysPage({ denied, mayEdit }: { denied: boolean; mayEdit: boolean }) {
  const queries = useQueryClient();
  const notify = useToast();
  const submission = useSubmissionKey();

  const gateways = useQuery({
    queryKey: ['payment-gateways'],
    queryFn: () => fetchPaymentGateways(),
    enabled: !denied,
  });

  /** Null while nothing is open; a provider while one route is being configured. */
  const [editing, setEditing] = useState<string | null>(null);
  const [form, setForm] = useState<FormState>(EMPTY_FORM);

  const rows = gateways.data?.gateways ?? [];
  /** Null while no key form is open; a provider while its API key is being replaced. */
  const [keying, setKeying] = useState<string | null>(null);
  /*
   * The key the operator is typing, and nowhere else: it is sent once, then cleared, and
   * the page never receives a key back to put here.
   */
  const [apiKey, setApiKey] = useState('');
  const keyed = useSubmissionKey();

  const reset = () => {
    setEditing(null);
    setForm(EMPTY_FORM);
  };

  const refresh = () => {
    void queries.invalidateQueries({ queryKey: ['payment-gateways'] });
  };

  const save = useMutation({
    mutationFn: () => {
      if (editing === null) throw new Error('nothing is being edited');
      /*
       * Refused here rather than rewritten. `minorOf` returns null for anything that is
       * not a whole number of minor units, and submitting a corrected value the operator
       * did not type is the failure it documents.
       */
      const min = minorOf(form.minAmountMinor);
      const max = minorOf(form.maxAmountMinor);
      if (min === null || max === null) {
        throw new Error(t('web.payment_gateway_amount_invalid'));
      }
      const gift = percentOf(form.topupCashbackPercent);
      if (gift === null) throw new Error(t('web.payment_gateway_topup_invalid'));
      const body = {
        provider: editing,
        displayName: form.displayName.trim() === '' ? null : form.displayName.trim(),
        instructions: form.instructions.trim() === '' ? null : form.instructions.trim(),
        minAmountMinor: min,
        maxAmountMinor: max,
        eligibility: {
          activateAfterPayments: counted(form.activateAfterPayments),
          deactivateAfterPayments: counted(form.deactivateAfterPayments),
          activateAfterAccountDays: counted(form.activateAfterAccountDays),
        },
        sortOrder: counted(form.sortOrder),
        /*
         * The route's top-up gift (Payment File 02 §17, D5), as the operator typed it and
         * `percentOf` accepted it. Each top-up snapshots it when created, so this changes
         * only top-ups created after the save.
         */
        topupCashbackPercent: gift,
        /*
         * Both switches, always, as the form shows them. The server defaults an ABSENT
         * switch to on for the previous release's client; a form that has the switch
         * and omitted it would silently turn a route back on for a purpose the
         * operator just switched off.
         */
        allowServicePurchase: form.allowServicePurchase,
        allowWalletTopup: form.allowWalletTopup,
      };
      /*
       * The key is bound to the whole payload AND to which route is being written, so
       * correcting a value and pressing save again is a NEW command rather than a replay
       * the store refuses as a payload mismatch.
       */
      return updatePaymentGateway({
        ...body,
        idempotencyKey: submission.current(body),
      });
    },
    onSuccess: () => {
      submission.settle();
      notify({ tone: 'ok', message: t('web.payment_gateway_saved') });
      reset();
      refresh();
    },
    // A 5xx may have committed. A fresh key on the retry would be a second command.
    onError: (error) => submission.settleOn(error),
  });

  const toggle = useMutation({
    mutationFn: (input: { provider: string; status: 'ACTIVE' | 'DISABLED' }) =>
      setPaymentGatewayStatus({
        ...input,
        idempotencyKey: submission.current({ status: input.status, provider: input.provider }),
      }),
    onSuccess: () => {
      submission.settle();
      notify({ tone: 'ok', message: t('web.payment_gateway_status_done') });
      refresh();
    },
    onError: (error) => submission.settleOn(error),
  });

  const credential = useMutation({
    mutationFn: () => {
      if (keying === null) throw new Error('no route is being keyed');
      return setPaymentGatewayCredential({
        provider: keying,
        apiKey,
        // A new key for a new value, so correcting a mistyped key is a new command.
        idempotencyKey: keyed.current({ provider: keying, apiKey }),
      });
    },
    onSuccess: () => {
      keyed.settle();
      setApiKey('');
      setKeying(null);
      notify({ tone: 'ok', message: t('web.payment_gateway_credential_saved') });
      refresh();
    },
    onError: (error) => keyed.settleOn(error),
  });

  const busy = save.isPending || toggle.isPending || credential.isPending;
  const failure = save.error ?? toggle.error;

  const columns: readonly Column<PaymentGatewayView>[] = [
    {
      key: 'name',
      header: t('web.payment_gateway_provider'),
      render: (row) => (
        <>
          {nameOf(row)}
          {row.displayName === null && (
            <>
              {' '}
              <Badge tone="neutral">{t('web.payment_gateway_name_default')}</Badge>
            </>
          )}
        </>
      ),
    },
    {
      key: 'state',
      header: t('web.payment_gateway_state'),
      render: (row) => (
        <Badge tone={row.status === 'ACTIVE' ? 'ok' : 'neutral'}>
          {t(
            row.status === 'ACTIVE' ? 'web.payment_gateway_active' : 'web.payment_gateway_disabled',
          )}
        </Badge>
      ),
    },
    {
      key: 'min',
      header: t('web.payment_gateway_min'),
      render: (row) => boundOf(row.minAmountMinor, row.currency),
    },
    {
      key: 'max',
      header: t('web.payment_gateway_max'),
      render: (row) => boundOf(row.maxAmountMinor, row.currency),
    },
    {
      key: 'eligibility',
      header: t('web.payment_gateway_eligibility'),
      /*
       * The thresholds as they are, and a dash when every one of them is off. Rendering
       * "0" three times would read as three conditions the operator has set to zero,
       * which is the opposite of what a zero means here.
       */
      render: (row) => {
        const parts = [
          row.eligibility.activateAfterPayments > 0
            ? `${t('web.payment_gateway_after_payments')}: ${row.eligibility.activateAfterPayments}`
            : null,
          row.eligibility.deactivateAfterPayments > 0
            ? `${t('web.payment_gateway_until_payments')}: ${row.eligibility.deactivateAfterPayments}`
            : null,
          row.eligibility.activateAfterAccountDays > 0
            ? `${t('web.payment_gateway_after_days')}: ${row.eligibility.activateAfterAccountDays}`
            : null,
        ].filter((part): part is string => part !== null);
        return parts.length === 0 ? '—' : parts.join(' · ');
      },
    },
    {
      key: 'gift',
      header: t('web.payment_gateway_topup_gift'),
      render: (row) =>
        row.topupCashbackPercent === 0 ? '—' : <Ltr>{`${String(row.topupCashbackPercent)}%`}</Ltr>,
    },
    {
      key: 'purposes',
      header: t('web.gateway_allow_column'),
      /*
       * Which purposes the route is on for. A route ACTIVE with both switches off is
       * offered for nothing, and that is said in amber rather than shown as an empty
       * cell an operator would read as "no restriction".
       */
      render: (row) => {
        const on = [
          row.allowServicePurchase ? t('web.gateway_allow_service_purchase') : null,
          row.allowWalletTopup ? t('web.gateway_allow_wallet_topup') : null,
        ].filter((label): label is string => label !== null);
        return on.length === 0 ? (
          <Badge tone="warn">{t('web.gateway_allow_none')}</Badge>
        ) : (
          on.join(' · ')
        );
      },
    },
    {
      key: 'credential',
      header: t('web.payment_gateway_credential'),
      /*
       * The STATE of the key, from its set-at time alone. The dots are a label, not a
       * value: there is no field here that holds or could resubmit anything.
       */
      render: (row) =>
        !row.credential.required ? (
          <span className="muted small">{t('web.payment_gateway_credential_none')}</span>
        ) : row.credential.setAt === null ? (
          <Badge tone="warn">{t('web.payment_gateway_credential_missing')}</Badge>
        ) : (
          <>
            <Badge tone="ok">{t('web.payment_gateway_credential_configured')}</Badge>{' '}
            <span className="muted small">{formatTimestamp(row.credential.setAt)}</span>
          </>
        ),
    },
    {
      key: 'updated',
      header: t('web.payment_gateway_updated'),
      render: (row) => formatTimestamp(row.updatedAt),
    },
    {
      key: 'actions',
      header: t('web.payment_gateway_actions'),
      align: 'end',
      // Nothing at all for a view-only role. The column header stays, because a table
      // whose columns depend on the reader is a table two operators describe differently.
      render: (row) =>
        !mayEdit ? null : (
          <div className="toolbar">
            <button
              type="button"
              className="btn sm"
              disabled={busy}
              onClick={() => {
                setEditing(row.provider);
                setForm(formOf(row));
              }}
            >
              {t('web.payment_gateway_edit')}
            </button>
            {row.credential.required && (
              <button
                type="button"
                className="btn sm"
                disabled={busy}
                onClick={() => {
                  setKeying(row.provider);
                  setApiKey('');
                }}
              >
                {t('web.payment_gateway_credential_edit')}
              </button>
            )}
            <button
              type="button"
              className="btn sm"
              disabled={busy}
              onClick={() =>
                toggle.mutate({
                  provider: row.provider,
                  status: row.status === 'ACTIVE' ? 'DISABLED' : 'ACTIVE',
                })
              }
            >
              {t(
                row.status === 'ACTIVE'
                  ? 'web.payment_gateway_disable'
                  : 'web.payment_gateway_enable',
              )}
            </button>
          </div>
        ),
    },
  ];

  return (
    <>
      <PageHead
        title={t('web.payment_gateways_title')}
        subtitle={t('web.payment_gateways_subtitle')}
        maturity="now"
      />

      <StateSwitch
        query={gateways}
        denied={denied}
        isEmpty={queryState(gateways) === 'ready' && rows.length === 0}
        empty={
          <Empty
            title={t('web.payment_gateways_empty')}
            hint={t('web.payment_gateways_empty_hint')}
          />
        }
      >
        <Card title={t('web.payment_gateways_title')} hint={t('web.payment_gateways_hint')}>
          <DataTable
            columns={columns}
            rows={rows}
            rowKey={(row) => row.provider}
            caption={t('web.payment_gateways_title')}
          />
        </Card>
      </StateSwitch>

      {/*
        The generated callback URLs, for diagnostics (WP11A §14). Read-only: the server
        builds them from the installation's registered public origin.
      */}
      {rows.some((row) => row.credential.required) && (
        <Card
          title={t('web.payment_gateway_callback_url')}
          hint={t('web.payment_gateway_callback_url_hint')}
        >
          {rows
            .filter((row) => row.credential.required)
            .map((row) => (
              <p key={row.provider}>
                <span className="strong">{nameOf(row)}</span>{' '}
                {row.callbackUrl === null ? (
                  <span className="muted small">{t('web.payment_gateway_callback_url_none')}</span>
                ) : (
                  <Ltr>{row.callbackUrl}</Ltr>
                )}
              </p>
            ))}
        </Card>
      )}

      {/*
        Replacing a route's API key. The input starts EMPTY every time: the stored key is
        never sent to this page, so there is nothing to prefill and nothing to reveal.
      */}
      {mayEdit && keying !== null && (
        <Card
          title={t('web.payment_gateway_credential_title')}
          hint={t('web.payment_gateway_credential_hint')}
        >
          <Field label={t('web.payment_gateway_credential_input')} htmlFor="pg-api-key">
            <input
              id="pg-api-key"
              type="password"
              autoComplete="new-password"
              spellCheck={false}
              value={apiKey}
              maxLength={512}
              onChange={(event) => setApiKey(event.target.value)}
            />
          </Field>
          <div className="toolbar">
            <button
              type="button"
              className="btn primary sm"
              disabled={busy || apiKey.trim() === ''}
              onClick={() => credential.mutate()}
            >
              {t('web.payment_gateway_credential_save')}
            </button>
            <button
              type="button"
              className="btn sm"
              disabled={busy}
              onClick={() => {
                setKeying(null);
                setApiKey('');
              }}
            >
              {t('web.payment_gateway_cancel_edit')}
            </button>
          </div>
          {credential.error != null && (
            <Banner tone="danger">{messageFor(credential.error)}</Banner>
          )}
        </Card>
      )}

      {/*
        A refusal to switch a route on — TonPays without its key — lands here, since the
        toggle has no form of its own.
      */}
      {editing === null && toggle.error != null && (
        <Banner tone="danger">{messageFor(toggle.error)}</Banner>
      )}

      {/*
        Only while a route is open. There is no "new route" form, because there is no
        create — the roster is what this release can operate.
      */}
      {mayEdit && editing !== null && (
        <Card title={t('web.payment_gateway_editing')} hint={t('web.payment_gateway_form_hint')}>
          <Field
            label={t('web.payment_gateway_name')}
            htmlFor="pg-name"
            hint={t('web.payment_gateway_name_hint')}
          >
            <input
              id="pg-name"
              value={form.displayName}
              maxLength={60}
              onChange={(event) => setForm({ ...form, displayName: event.target.value })}
            />
          </Field>

          <Field
            label={t('web.payment_gateway_instructions')}
            htmlFor="pg-instructions"
            hint={t('web.payment_gateway_instructions_hint')}
          >
            <textarea
              id="pg-instructions"
              rows={3}
              value={form.instructions}
              maxLength={1000}
              onChange={(event) => setForm({ ...form, instructions: event.target.value })}
            />
          </Field>

          <Field
            label={t('web.payment_gateway_min')}
            htmlFor="pg-min"
            hint={t('web.payment_gateway_amount_hint')}
          >
            <input
              id="pg-min"
              value={form.minAmountMinor}
              inputMode="numeric"
              onChange={(event) => setForm({ ...form, minAmountMinor: event.target.value })}
            />
          </Field>
          <Field label={t('web.payment_gateway_max')} htmlFor="pg-max">
            <input
              id="pg-max"
              value={form.maxAmountMinor}
              inputMode="numeric"
              onChange={(event) => setForm({ ...form, maxAmountMinor: event.target.value })}
            />
          </Field>

          <Field
            label={t('web.payment_gateway_after_payments')}
            htmlFor="pg-after-payments"
            hint={t('web.payment_gateway_eligibility_hint')}
          >
            <input
              id="pg-after-payments"
              value={form.activateAfterPayments}
              inputMode="numeric"
              onChange={(event) => setForm({ ...form, activateAfterPayments: event.target.value })}
            />
          </Field>
          <Field label={t('web.payment_gateway_until_payments')} htmlFor="pg-until-payments">
            <input
              id="pg-until-payments"
              value={form.deactivateAfterPayments}
              inputMode="numeric"
              onChange={(event) =>
                setForm({ ...form, deactivateAfterPayments: event.target.value })
              }
            />
          </Field>
          <Field label={t('web.payment_gateway_after_days')} htmlFor="pg-after-days">
            <input
              id="pg-after-days"
              value={form.activateAfterAccountDays}
              inputMode="numeric"
              onChange={(event) =>
                setForm({ ...form, activateAfterAccountDays: event.target.value })
              }
            />
          </Field>

          <Field
            label={t('web.payment_gateway_topup_gift')}
            htmlFor="pg-topup-gift"
            hint={t('web.payment_gateway_topup_gift_hint')}
            {...(percentOf(form.topupCashbackPercent) === null
              ? { error: t('web.payment_gateway_topup_invalid') }
              : {})}
          >
            <input
              id="pg-topup-gift"
              value={form.topupCashbackPercent}
              inputMode="numeric"
              maxLength={4}
              onChange={(event) => setForm({ ...form, topupCashbackPercent: event.target.value })}
            />
          </Field>

          <Field label={t('web.gateway_allow_column')} hint={t('web.gateway_allow_hint')}>
            <div className="toolbar">
              <Switch
                checked={form.allowServicePurchase}
                onChange={(next) => setForm({ ...form, allowServicePurchase: next })}
                label={t('web.gateway_allow_service_purchase')}
              />
              <span>{t('web.gateway_allow_service_purchase')}</span>
            </div>
            <div className="toolbar">
              <Switch
                checked={form.allowWalletTopup}
                onChange={(next) => setForm({ ...form, allowWalletTopup: next })}
                label={t('web.gateway_allow_wallet_topup')}
              />
              <span>{t('web.gateway_allow_wallet_topup')}</span>
            </div>
          </Field>

          <Field label={t('web.payment_gateway_sort')} htmlFor="pg-sort">
            <input
              id="pg-sort"
              value={form.sortOrder}
              inputMode="numeric"
              onChange={(event) => setForm({ ...form, sortOrder: event.target.value })}
            />
          </Field>

          <div className="toolbar">
            <button
              type="button"
              className="btn primary sm"
              disabled={busy || percentOf(form.topupCashbackPercent) === null}
              onClick={() => save.mutate()}
            >
              {t('web.payment_gateway_save')}
            </button>
            <button type="button" className="btn sm" disabled={busy} onClick={reset}>
              {t('web.payment_gateway_cancel_edit')}
            </button>
          </div>

          {/*
            The server refuses a window that admits nothing — a maximum below the
            minimum, or payment-count bounds that cross — and the operator is told here.
            NOT pre-checked in the browser, deliberately: a second opinion about what a
            valid route is would be the one nobody tests.
          */}
          {failure != null && <Banner tone="danger">{messageFor(failure)}</Banner>}
        </Card>
      )}
    </>
  );
}
